/*
	Insert for Trainer Table
*/

INSERT INTO Trainer VALUES('Dr. Abby', 'Doctor');
INSERT INTO Trainer VALUES('Abigail', 'Basic');
INSERT INTO Trainer VALUES('Greta', 'Arena Tycoon');
INSERT INTO Trainer VALUES('Queen Ilene', 'Basic');
INSERT INTO Trainer VALUES('Officer Jenny', 'Basic');
INSERT INTO Trainer VALUES('Katie', 'Cooltrainer');
INSERT INTO Trainer VALUES('May', 'Coordinator');
INSERT INTO Trainer VALUES('Mona', 'Basic');
INSERT INTO Trainer VALUES('Solana', 'Pokemon Ranger');
INSERT INTO Trainer VALUES('Phoebe', 'Elite Four');
INSERT INTO Trainer VALUES('Annie Proctor', 'Pokemon Researcher');
INSERT INTO Trainer VALUES('Ramona', 'Basic');
INSERT INTO Trainer VALUES('Temacu', 'Basic');
INSERT INTO Trainer VALUES('Nini', 'Basic');
INSERT INTO Trainer VALUES('Suzy', 'Basic');
INSERT INTO Trainer VALUES('Ursula', 'Coordinator');
INSERT INTO Trainer VALUES('Zoey', 'Coordinator');
INSERT INTO Trainer VALUES('Zinnia', 'Basic');
INSERT INTO Trainer VALUES('Yoko', 'Basic');
INSERT INTO Trainer VALUES('Yvette', 'Sky Trainer');
INSERT INTO Trainer VALUES('Yuuko', 'Basic');
INSERT INTO Trainer VALUES('Yuki', 'Basic');
INSERT INTO Trainer VALUES('Yellow', 'Basic');
INSERT INTO Trainer VALUES('Yancy', 'Pokemon Trader');
INSERT INTO Trainer VALUES('Yai Suba', 'Basic');
INSERT INTO Trainer VALUES('Yvonne Gabena', 'Sky Trainer');
INSERT INTO Trainer VALUES('Winona', 'Gym Leader');
INSERT INTO Trainer VALUES('Whitney', 'Gym Leader');
INSERT INTO Trainer VALUES('Violet', 'Gym Leader');
INSERT INTO Trainer VALUES('Venus', 'Cipher Admin');
INSERT INTO Trainer VALUES('Valerie', 'Gym Leader');
INSERT INTO Trainer VALUES('Ultima', 'Basic');
INSERT INTO Trainer VALUES('Tyra', 'Basic');
INSERT INTO Trainer VALUES('Trixie', 'Basic');
INSERT INTO Trainer VALUES('Trinity', 'Water-type Expert');
INSERT INTO Trainer VALUES('Thief', 'Dark-Type Trainer');
INSERT INTO Trainer VALUES('Taylor', 'Colosseum');
INSERT INTO Trainer VALUES('Kidd Summers', 'Basic');
INSERT INTO Trainer VALUES('Summer', 'Pokemon Ranger');
INSERT INTO Trainer VALUES('Stephanie', 'Basic');
INSERT INTO Trainer VALUES('Stella', 'Circus Ringmaster');
INSERT INTO Trainer VALUES('Millis Steel', 'Basic');
INSERT INTO Trainer VALUES('Spring', 'Basic');
INSERT INTO Trainer VALUES('Summer', 'Basic');
INSERT INTO Trainer VALUES('Skyla', 'Gym Leader');
INSERT INTO Trainer VALUES('Sabrina','Gym Leader');
INSERT INTO Trainer VALUES('Nancy', 'Water Trainer');
INSERT INTO Trainer VALUES('Lila', 'Basic');
INSERT INTO Trainer VALUES('Haley', 'Basic');
INSERT INTO Trainer VALUES('Lenora', 'Gym Leader');
INSERT INTO Trainer VALUES('Ginger', 'Basic');
INSERT INTO Trainer VALUES('Autumn', 'Basic');
INSERT INTO Trainer VALUES('Arielle', 'Basic');
INSERT INTO Trainer VALUES('Bianca', 'Basic');
INSERT INTO Trainer VALUES('Billy Jo', 'Basic');
INSERT INTO Trainer VALUES('Allegra', 'Coordinator');
INSERT INTO Trainer VALUES('Cassidy', 'Team Rocket');
INSERT INTO Trainer VALUES('Jessie', 'Team Rocket');
INSERT INTO Trainer VALUES('Juliet', 'Basic');
INSERT INTO Trainer VALUES('Iris', 'Champion');
INSERT INTO Trainer VALUES('Giselle', 'Basic');
INSERT INTO Trainer VALUES('Mars', 'Team Galactic');
INSERT INTO Trainer VALUES('Jessebelle', 'Basic');
INSERT INTO Trainer VALUES('Maisy', 'Basic');
INSERT INTO Trainer VALUES('Luna', 'Basic');
INSERT INTO Trainer VALUES('Janet', 'Basic');
INSERT INTO Trainer VALUES('Cassandra', 'Basic');
INSERT INTO Trainer VALUES('Aldith', 'Team Plasma');
INSERT INTO Trainer VALUES('Celosia', 'Team Flare');
INSERT INTO Trainer VALUES('Bailey', 'Grass Trainer');
INSERT INTO Trainer VALUES('Ellie', 'Rancher');
INSERT INTO Trainer VALUES('Flora', 'Basic');
INSERT INTO Trainer VALUES('Gemma', 'Basic');
INSERT INTO Trainer VALUES('Georgia', 'Dragon Buster');
INSERT INTO Trainer VALUES('Gail', 'Basic');
INSERT INTO Trainer VALUES('Carlita', 'Basic');
INSERT INTO Trainer VALUES('Caitlin', 'Elite Four');
INSERT INTO Trainer VALUES('Bebe', 'Basic');
INSERT INTO Trainer VALUES('Aaron', 'Elite Four');
INSERT INTO Trainer VALUES('Agatha', 'Elite Four');
INSERT INTO Trainer VALUES('Blaine', 'Gym Leader');
INSERT INTO Trainer VALUES('Blue', 'Champion');
INSERT INTO Trainer VALUES('Brawly', 'Gym Leader');
INSERT INTO Trainer VALUES('Brock', 'Gym Leader');
INSERT INTO Trainer VALUES('Brycen', 'Gym Leader');
INSERT INTO Trainer VALUES('Bugsy', 'Gym Leader');
INSERT INTO Trainer VALUES('Burgh', 'Gym Leader');
INSERT INTO Trainer VALUES('Byron', 'Gym Leader');
INSERT INTO Trainer VALUES('Candice', 'Gym Leader');
INSERT INTO Trainer VALUES('Cheren', 'Gym Leader');
INSERT INTO Trainer VALUES('Chili', 'Gym Leader');
INSERT INTO Trainer VALUES('Chuck', 'Gym Leader');
INSERT INTO Trainer VALUES('Cilan', 'Gym Leader');
INSERT INTO Trainer VALUES('Cissy', 'Gym Leader');
INSERT INTO Trainer VALUES('Clair', 'Gym Leader');
INSERT INTO Trainer VALUES('Clay', 'Gym Leader');
INSERT INTO Trainer VALUES('Cress', 'Gym Leader');
INSERT INTO Trainer VALUES('Daisy', 'Gym Leader');
INSERT INTO Trainer VALUES('Danny', 'Gym Leader');
INSERT INTO Trainer VALUES('Drayden', 'Gym Leader');
INSERT INTO Trainer VALUES('Elesa', 'Gym Leader');
INSERT INTO Trainer VALUES('Erika', 'Gym Leader');
INSERT INTO Trainer VALUES('Falkner', 'Gym Leader');
INSERT INTO Trainer VALUES('Fantina', 'Gym Leader');
INSERT INTO Trainer VALUES('Flannery', 'Gym Leader');
INSERT INTO Trainer VALUES('Flint', 'Gym Leader');
INSERT INTO Trainer VALUES('Forrest', 'Gym Leader');
INSERT INTO Trainer VALUES('Gardenia', 'Gym Leader');
INSERT INTO Trainer VALUES('Giovanni', 'Gym Leader');
INSERT INTO Trainer VALUES('Grant', 'Gym Leader');
INSERT INTO Trainer VALUES('James', 'Team Rocket');
INSERT INTO Trainer VALUES('Janine', 'Gym Leader');
INSERT INTO Trainer VALUES('Jasmine', 'Gym Leader');
INSERT INTO Trainer VALUES('Jaun', 'Gym Leader');
INSERT INTO Trainer VALUES('Kaz', 'Gym Leader');
INSERT INTO Trainer VALUES('Kiyo', 'Karate Master');
INSERT INTO Trainer VALUES('Koga', 'Gym Leader');
INSERT INTO Trainer VALUES('Korrina', 'Gym Leader');
INSERT INTO Trainer VALUES('Lily', 'Gym Leader');
INSERT INTO Trainer VALUES('Lola', 'Gym Leader');
INSERT INTO Trainer VALUES('Luana', 'Gym Leader');
INSERT INTO Trainer VALUES('Marlon', 'Gym Leader');
INSERT INTO Trainer VALUES('Maylene', 'Gym Leader');
INSERT INTO Trainer VALUES('Misty', 'Gym Leader');
INSERT INTO Trainer VALUES('Mr. Moore', 'Gym Leader');
INSERT INTO Trainer VALUES('Morty', 'Gym Leader');
INSERT INTO Trainer VALUES('Norman', 'Gym Leader');
INSERT INTO Trainer VALUES('Olympia', 'Gym Leader');
INSERT INTO Trainer VALUES('Pryce', 'Gym Leader');
INSERT INTO Trainer VALUES('Ramos', 'Gym Leader');
INSERT INTO Trainer VALUES('Roark', 'Gym Leader');
INSERT INTO Trainer VALUES('Roxanne', 'Gym Leader');
INSERT INTO Trainer VALUES('Roxie', 'Gym Leader');
INSERT INTO Trainer VALUES('Rudy', 'Gym Leader');
INSERT INTO Trainer VALUES('Lt. Surge', 'Gym Leader');
INSERT INTO Trainer VALUES('Tate & Liza', 'Gym Leader');
INSERT INTO Trainer VALUES('Viola', 'Gym Leader');
INSERT INTO Trainer VALUES('Volkner', 'Gym Leader');
INSERT INTO Trainer VALUES('Crasher Wake', 'Gym Leader');
INSERT INTO Trainer VALUES('Wallace', 'Champion');
INSERT INTO Trainer VALUES('Wattson', 'Gym Leader');
INSERT INTO Trainer VALUES('Wulfric', 'Gym Leader');
INSERT INTO Trainer VALUES('Yas', 'Gym Leader');
