/*
	Insert for Trainer Table
*/

INSERT INTO Trainer VALUES('Dr. Abby', 'Doctor');
INSERT INTO Trainer VALUES('Abigail', 'Basic');
INSERT INTO Trainer VALUES('Greta', 'Arena Tycoon');
INSERT INTO Trainer VALUES('Queen Ilene', 'Basic');
INSERT INTO Trainer VALUES('Professor Ivy', 'Pokemon Professor');
INSERT INTO Trainer VALUES('Officer Jenny', 'Basic');
INSERT INTO Trainer VALUES('Katie', 'Cooltrainer');
INSERT INTO Trainer VALUES('May', 'Coordinator');
INSERT INTO Trainer VALUES('Mona', 'Basic');
INSERT INTO Trainer VALUES('Misty', 'Gym Leader');
INSERT INTO Trainer VALUES('Solana', 'Pokemon Ranger');
INSERT INTO Trainer VALUES('Phoebe', 'Elite Four');
INSERT INTO Trainer VALUES('Annie Proctor ', 'Pokemon Researcher');
INSERT INTO Trainer VALUES('Ramona', 'Basic');
INSERT INTO Trainer VALUES('Temacu', 'Basic');
INSERT INTO Trainer VALUES('Nini', 'Basic');
INSERT INTO Trainer VALUES('Suzy', 'Basic');
INSERT INTO Trainer VALUES('Tammy', 'Basic');
INSERT INTO Trainer VALUES('Reina', 'Basic');
INSERT INTO Trainer VALUES('Ursula', 'Coordinator');
INSERT INTO Trainer VALUES('Zoey', 'Coordinator');
INSERT INTO Trainer VALUES('Zinnia', 'Basic');
INSERT INTO Trainer VALUES('Yoko', 'Basic');
INSERT INTO Trainer VALUES('Yvette', 'Sky Trainer');
INSERT INTO Trainer VALUES('Yuuko', 'Basic');
INSERT INTO Trainer VALUES('Yuki', 'Basic');
INSERT INTO Trainer VALUES('Yellow', 'Basic');
INSERT INTO Trainer VALUES('Yancy', 'Pokemon Trader');
INSERT INTO Trainer VALUES('Yai Suba', 'Basic');
INSERT INTO Trainer VALUES('Yvonne Gabena', 'Sky Trainer');
INSERT INTO Trainer VALUES('Winona', 'Gym Leader');
INSERT INTO Trainer VALUES('Wilma', 'Move Tutor');
INSERT INTO Trainer VALUES('Wilhelmina', 'Basic');
INSERT INTO Trainer VALUES('Whitney', 'Gym Leader');
INSERT INTO Trainer VALUES('White', 'Basic');
INSERT INTO Trainer VALUES('Whi-Two', 'Basic');
INSERT INTO Trainer VALUES('Wendy', 'Pokemon Ranger');
INSERT INTO Trainer VALUES('Wanda', 'Basic');
INSERT INTO Trainer VALUES('Wakaba', 'Basic');
INSERT INTO Trainer VALUES('Vivica', 'Basic');
INSERT INTO Trainer VALUES('Violet', 'Gym Leader');
INSERT INTO Trainer VALUES('Verona', 'Forest Ranger');
INSERT INTO Trainer VALUES('Venus', 'Cipher Admin');
INSERT INTO Trainer VALUES('Valerie', 'Gym Leader');
INSERT INTO Trainer VALUES('Ultima', 'Basic');
INSERT INTO Trainer VALUES('Tyra', 'Basic');
INSERT INTO Trainer VALUES('Trixie', 'Basic');
INSERT INTO Trainer VALUES('Trinity', 'Water-type Expert');
INSERT INTO Trainer VALUES('The Thief', 'Dark-Type Trainer');
INSERT INTO Trainer VALUES('Terri', 'Basic');
INSERT INTO Trainer VALUES('Alice Telesu', 'Basic');
INSERT INTO Trainer VALUES('Taylor', 'Colosseum');
INSERT INTO Trainer VALUES('Kidd Summers', 'Basic');
INSERT INTO Trainer VALUES('Summer', 'Pokemon Ranger');
INSERT INTO Trainer VALUES('Stephanie', 'Basic');
INSERT INTO Trainer VALUES('Stella', 'Circus Ringmaster');
INSERT INTO Trainer VALUES('Millis Steel', 'Basic');
INSERT INTO Trainer VALUES('Spring', 'Basic');
INSERT INTO Trainer VALUES('Summer', 'Basic');
INSERT INTO Trainer VALUES('Sophia', 'Basic');
INSERT INTO Trainer VALUES('Sonrisa', 'Basic');
INSERT INTO Trainer VALUES('Solidad', 'Coordinator');
INSERT INTO Trainer VALUES('Skyla', 'Gym Leader');
INSERT INTO Trainer VALUES('Sird', 'Team Rocket');
INSERT INTO Trainer VALUES('Shoko', 'Basic');
INSERT INTO Trainer VALUES('Shione', 'Fairy Trainer');
INSERT INTO Trainer VALUES('Shelly', 'Aqua Admin');
INSERT INTO Trainer VALUES('Shauntal', 'Elite Four');
INSERT INTO Trainer VALUES('Nancy', 'Water Trainer');
INSERT INTO Trainer VALUES('Lila', 'Basic');
INSERT INTO Trainer VALUES('Haley', 'Basic');
INSERT INTO Trainer VALUES('Lenora', 'Gym Leader');
INSERT INTO Trainer VALUES('Ginger', 'Basic');
INSERT INTO Trainer VALUES('Autumn', 'Basic');
INSERT INTO Trainer VALUES('Arielle', 'Basic');
INSERT INTO Trainer VALUES('Bianca', 'Basic');
INSERT INTO Trainer VALUES('Billy Jo', 'Basic');
INSERT INTO Trainer VALUES('Allegra', 'Coordinator');
INSERT INTO Trainer VALUES('Cassidy', 'Team Rocket');
INSERT INTO Trainer VALUES('Jessie', 'Team Rocket');
INSERT INTO Trainer VALUES('Juliet', 'Basic');
INSERT INTO Trainer VALUES('Iris', 'Champion');
INSERT INTO Trainer VALUES('Giselle', 'Basic');
INSERT INTO Trainer VALUES('Hayley', 'Basic');
INSERT INTO Trainer VALUES('Mars', 'Team Galactic');
INSERT INTO Trainer VALUES('Jessebelle', 'Basic');
INSERT INTO Trainer VALUES('Maisy', 'Basic');
INSERT INTO Trainer VALUES('Luna', 'Basic');
INSERT INTO Trainer VALUES('Janet', 'Basic');
INSERT INTO Trainer VALUES('Cassandra', 'Basic');
INSERT INTO Trainer VALUES('Aldith', 'Team Plasma');
INSERT INTO Trainer VALUES('Celosia', 'Team Flare');
INSERT INTO Trainer VALUES('Bailey', 'Grass Trainer');
INSERT INTO Trainer VALUES('Ellie', 'Rancher');
INSERT INTO Trainer VALUES('Flora', 'Basic');
INSERT INTO Trainer VALUES('Gemma', 'Basic');
INSERT INTO Trainer VALUES('Georgia', 'Dragon Buster');
INSERT INTO Trainer VALUES('Gardenia', 'Gym Leader');
INSERT INTO Trainer VALUES('Gail', 'Basic');
INSERT INTO Trainer VALUES('Carlita', 'Basic');
INSERT INTO Trainer VALUES('Caitlin', 'Elite Four');
INSERT INTO Trainer VALUES('Bebe', 'Basic');
