/*
  Insert into Pokemon table
*/

INSERT INTO Pokemon VALUES(1, 'Bulbasaur', 'B', 'Seed', FALSE, 'Overgrow');
INSERT INTO Pokemon VALUES(2, 'Ivysaur', 'B', 'Seed', TRUE, 'Overgrow');
INSERT INTO Pokemon VALUES(3, 'Venusaur', 'B', 'Seed', TRUE, 'Overgrow');
INSERT INTO Pokemon VALUES(4, 'Charmander', 'B', 'Lizard', FALSE, 'Blaze');
INSERT INTO Pokemon VALUES(5, 'Charmeleon', 'B', 'Flame', TRUE, 'Blaze');
INSERT INTO Pokemon VALUES(6, 'Charizard', 'B', 'Flame', TRUE, 'Blaze');
INSERT INTO Pokemon VALUES(7, 'Squirtle', 'B', 'Tiny Turtle', FALSE, 'Torrent');
INSERT INTO Pokemon VALUES(8, 'Wartortle', 'B', 'Turtle', TRUE, 'Torrent');
INSERT INTO Pokemon VALUES(9, 'Blastoise', 'B', 'Shellfish', TRUE, 'Torrent');
INSERT INTO Pokemon VALUES(10, 'Caterpie', 'B', 'Worm', FALSE, 'Shield Dust');
INSERT INTO Pokemon VALUES(11, 'Metapod', 'B', 'Cocoon', TRUE, 'Shed Skin');
INSERT INTO Pokemon VALUES(12, 'Butterfree', 'B', 'Butterfly', TRUE, 'Compound Eyes');
INSERT INTO Pokemon VALUES(13, 'Weedle', 'B', 'Hairy Bug', FALSE, 'Shield Dust');
INSERT INTO Pokemon VALUES(14, 'Kakuna', 'B', 'Cocoon', TRUE, 'Shed Skin');
INSERT INTO Pokemon VALUES(15, 'Beedrill', 'B', 'Poison Bee', TRUE, 'Swarm');
INSERT INTO Pokemon VALUES(16, 'Pidgey', 'B', 'Tiny Bird', FALSE, 'Keen Eye');
INSERT INTO Pokemon VALUES(17, 'Pidgeotto', 'B', 'Bird', TRUE, 'Keen Eye');
INSERT INTO Pokemon VALUES(18, 'Pidgeot', 'B', 'Bird', TRUE, 'Keen');
INSERT INTO Pokemon VALUES(19, 'Rattata', 'B', 'Mouse', FALSE, 'Run Away');
INSERT INTO Pokemon VALUES(20, 'Raticate', 'B', 'Mouse', TRUE, 'Run Away');
INSERT INTO Pokemon VALUES(21, 'Spearow', 'B', 'Tiny Bird', FALSE, 'Keen Eye');
INSERT INTO Pokemon VALUES(22, 'Fearow', 'B', 'Beak', TRUE, 'Keen Eye');
INSERT INTO Pokemon VALUES(23, 'Ekans', 'B', 'Snake', FALSE, 'Shed Skin');
INSERT INTO Pokemon VALUES(24, 'Arbok', 'B', 'Cobra', TRUE, 'Intimidate');
INSERT INTO Pokemon VALUES(25, 'Pikachu', 'B', 'Mouse', TRUE, 'Static');
INSERT INTO Pokemon VALUES(26, 'Raichu', 'B', 'Mouse', TRUE, 'Static');
INSERT INTO Pokemon VALUES(27, 'Sandshrew', 'B', 'Mouse', FALSE, 'Sand Veil');
INSERT INTO Pokemon VALUES(28, 'Sandslash', 'B', 'Mouse', TRUE, 'Sand Veil');
INSERT INTO Pokemon VALUES(29, 'Nidoran', 'F', 'Poison Pin', FALSE, 'Poison Point');
INSERT INTO Pokemon VALUES(30, 'Nidorina', 'F', 'Poison Pin', TRUE, 'Poison Point');
INSERT INTO Pokemon VALUES(31, 'Nidoqueen', 'F', 'Drill', TRUE, 'Rivalry');
INSERT INTO Pokemon VALUES(32, 'Nidoran', 'M', 'Poison Pin', FALSE, 'Poison Point');
INSERT INTO Pokemon VALUES(33, 'Nidorano', 'M', 'Poison Pin', TRUE, 'Poison Point');
INSERT INTO Pokemon VALUES(34, 'Nidoking', 'M', 'Drill', TRUE, 'Rivalry');
INSERT INTO Pokemon VALUES(35, 'Clefairy', 'B', 'Fairy', TRUE, 'Cute Charm');
INSERT INTO Pokemon VALUES(36, 'Clefable', 'B', 'Fairy', TRUE, 'Magic Guard');
INSERT INTO Pokemon VALUES(37, 'Vulpix', 'B', 'Fox', FALSE, 'Flash Fire');
INSERT INTO Pokemon VALUES(38, 'Ninetails', 'B', 'Fox', TRUE, 'Flash Fire');
INSERT INTO Pokemon VALUES(39, 'Jigglypuff', 'B', 'Balloon', TRUE, 'Competitive');
INSERT INTO Pokemon VALUES(40, 'Wigglytuff', 'B', 'Balloon', TRUE, 'Competitive');
INSERT INTO Pokemon VALUES(41, 'Zubat', 'B', 'Bat', FALSE, 'Inner Focus');
INSERT INTO Pokemon VALUES(42, 'Golbat', 'B', 'Bat', TRUE, 'Inner Focus');
INSERT INTO Pokemon VALUES(43, 'Oddish', 'B', 'Weed', FALSE, 'Chlorophyll');
INSERT INTO Pokemon VALUES(44, 'Gloom', 'B', 'Weed', TRUE, 'Chlorophyll');
INSERT INTO Pokemon VALUES(45, 'Vileplume', 'B', 'Flower', TRUE, 'Chlorophyll');
INSERT INTO Pokemon VALUES(46, 'Paras', 'B', 'Mushroom', FALSE, 'Effect Spore');
INSERT INTO Pokemon VALUES(47, 'Parasect', 'B', 'Mushroom', TRUE, 'Dry Skin');
INSERT INTO Pokemon VALUES(48, 'Venonat', 'B', 'Insect', FALSE, 'Effect Spore');
INSERT INTO Pokemon VALUES(49, 'Venomoth', 'B', 'Poison Moth', TRUE, 'Sheld Dust');
INSERT INTO Pokemon VALUES(50, 'Diglett', 'B', 'Mole', FALSE, 'Sand Veil');
INSERT INTO Pokemon VALUES(51, 'Dugtrio', 'B', 'Mole', TRUE, 'Arena Trap');
INSERT INTO Pokemon VALUES(52, 'Meowth', 'B', 'Scratch  Cat', FALSE, 'Pick Up');
INSERT INTO Pokemon VALUES(53, 'Persian', 'B', 'Classy Cat', TRUE, 'Limber');
INSERT INTO Pokemon VALUES(54, 'Psyduck', 'B', 'Duck', FALSE, 'Damp');
INSERT INTO Pokemon VALUES(55, 'Golduck', 'B', 'Duck', TRUE, 'Cloud Nine');
INSERT INTO Pokemon VALUES(56, 'Mankey', 'B', 'Pig Monkey', FALSE, 'Vital Spirit');
INSERT INTO Pokemon VALUES(57, 'Primeape', 'B', 'Pig Monkey', TRUE, 'Anger Point');
INSERT INTO Pokemon VALUES(58, 'Growlithe', 'B', 'Puppy', FALSE, 'Intimidate');
INSERT INTO Pokemon VALUES(59, 'Arcanine', 'B', 'Legendary', TRUE, 'Flash Fire');
INSERT INTO Pokemon VALUES(60, 'Poliwag', 'B', 'Tadpole',	FALSE,'Damp');
INSERT INTO Pokemon VALUES(61, 'Poliwhirl', 'B', 'Tadpole', TRUE, 'Damp');
INSERT INTO Pokemon VALUES(62, 'Poliwrath', 'B', 'Tadpole', TRUE, 'Water Absorb');
INSERT INTO Pokemon VALUES(63, 'Abra', 'B', 'Psi', FALSE, 'Inner Focus');
INSERT INTO Pokemon VALUES(64, 'Kadabra', 'B', 'Psi', TRUE, 'Inner Focus');
INSERT INTO Pokemon VALUES(65, 'Alakazam', 'B', 'Psi', TRUE, 'Synchronize');
INSERT INTO Pokemon VALUES(66, 'Machop', 'B', 'Superpower', FALSE, 'Guts');
INSERT INTO Pokemon VALUES(67, 'Machoke', 'B', 'Superpower', TRUE, 'No Guard');
INSERT INTO Pokemon VALUES(68, 'Machamp', 'B', 'Superpower', TRUE, 'No Guard');
INSERT INTO Pokemon VALUES(69, 'Bellsprout', 'B', 'Flower', FALSE, 'Chlorophyll');
INSERT INTO Pokemon VALUES(70, 'Weepinbell', 'B', 'Flycatcher', TRUE, 'Chlorophyll');
INSERT INTO Pokemon VALUES(71, 'Victreebel', 'B', 'Flycatcher', TRUE, 'Chlorophyll');
INSERT INTO Pokemon VALUES(72, 'Tentacool', 'B', 'Jellyfish', FALSE, 'Clear Body');
INSERT INTO Pokemon VALUES(73, 'Tentacruel', 'B', 'Jellyfish', TRUE, 'Liquid Ooze');
INSERT INTO Pokemon VALUES(74, 'Geodude', 'B', 'Rock', FALSE, 'Rock Head');
INSERT INTO Pokemon VALUES(75, 'Graveler', 'B', 'Rock', TRUE, 'Rock Head');
INSERT INTO Pokemon VALUES(76, 'Golem', 'B', 'Rock', TRUE, 'Sturdy');
INSERT INTO Pokemon VALUES(77, 'Ponyta', 'B', 'Fire Horse', FALSE, 'Run Away');
INSERT INTO Pokemon VALUES(78, 'Rapidash', 'B', 'Fire Horse', TRUE, 'Flash Fire');
INSERT INTO Pokemon VALUES(79, 'Slowpoke', 'B', 'Dopey', FALSE, 'Oblivious');
INSERT INTO Pokemon VALUES(80, 'Slowbro', 'B', 'Hermit Crab', TRUE, 'Own Tempo');
INSERT INTO Pokemon VALUES(81, 'Magnemite', 'U', 'Magnet', FALSE, 'Sturdy');
INSERT INTO Pokemon VALUES(82, 'Magneton', 'U', 'Magnet', TRUE, 'Magnet Pull');
INSERT INTO Pokemon VALUES(83, 'Farfetchd', 'B', 'Wild Duck', FALSE, 'Inner Focus');
INSERT INTO Pokemon VALUES(84, 'Doduo', 'B', 'Twin Bird', FALSE, 'Run Away');
INSERT INTO Pokemon VALUES(85, 'Dodrio', 'B', 'Triple Bird', TRUE, 'Early Bird');
INSERT INTO Pokemon VALUES(86, 'Seel', 'B', 'Sea Lion', FALSE, 'Thick Fat');
INSERT INTO Pokemon VALUES(87, 'Dewgong', 'B', 'Sea Lion', TRUE, 'Hydration');
INSERT INTO Pokemon VALUES(88, 'Grimer', 'B', 'Sludge', FALSE, 'Stench');
INSERT INTO Pokemon VALUES(89, 'Muk', 'B', 'Sludge', TRUE, 'Sticky Hold');
INSERT INTO Pokemon VALUES(90, 'Shellder', 'B', 'Bivalve', FALSE, 'Shell Armor');
INSERT INTO Pokemon VALUES(91, 'Cloyster', 'B', 'Bivalve', TRUE, 'Skill Link');
INSERT INTO Pokemon VALUES(92, 'Gastly', 'B', 'Gas', FALSE, 'Levitate');
INSERT INTO Pokemon VALUES(93, 'Haunter', 'B', 'Gas', TRUE, 'Levitate');
INSERT INTO Pokemon VALUES(94, 'Gengar', 'B', 'Shadow', TRUE, 'Levitate');
INSERT INTO Pokemon VALUES(95, 'Onix', 'B', 'Rock Snake', FALSE, 'Rock Head');
INSERT INTO Pokemon VALUES(96, 'Drowzee', 'B', 'Hypnosis', FALSE, 'Insomnia');
INSERT INTO Pokemon VALUES(97, 'Hypno', 'B', 'Hypnosis', TRUE, 'Forewarn');
INSERT INTO Pokemon VALUES(98, 'Krabby', 'B', 'River Crab', FALSE, 'Shell Armor');
INSERT INTO Pokemon VALUES(99, 'Kingler', 'B', 'Pincer', TRUE, 'Hyper Cutter');
INSERT INTO Pokemon VALUES(100, 'Voltorb', 'U', 'Ball', FALSE, 'Static');
INSERT INTO Pokemon VALUES(101, 'Electrode', 'U', 'Ball', TRUE, 'Soundproof');
INSERT INTO Pokemon VALUES(102, 'Exeggcute', 'B', 'Egg', FALSE, 'Chlorophyll');
INSERT INTO Pokemon VALUES(103, 'Exeggutor', 'B', 'Coconut', TRUE, 'Chlorophyll');
INSERT INTO Pokemon VALUES(104, 'Cubone', 'B', 'Lonely', FALSE, 'Rock Head');
INSERT INTO Pokemon VALUES(105, 'Marowak', 'B', 'Bone Keeper', TRUE, 'Lightning Rod');
INSERT INTO Pokemon VALUES(106, 'Hitmonlee', 'M', 'Kicking', TRUE, 'Reckless');
INSERT INTO Pokemon VALUES(107, 'Hitmonchan', 'M', 'Punching', TRUE, 'Iron Fist');
INSERT INTO Pokemon VALUES(108, 'Lickitung', 'B', 'Licking', FALSE, 'Own Tempo');
INSERT INTO Pokemon VALUES(109, 'Koffing', 'B', 'Poison Gas', FALSE, 'Levitate');
INSERT INTO Pokemon VALUES(110, 'Weezing', 'B', 'Poison Gas', TRUE, 'Levitate');
INSERT INTO Pokemon VALUES(111, 'Rhyhorn', 'B', 'Spikes', FALSE, 'Rock Head');
INSERT INTO Pokemon VALUES(112, 'Rhydon', 'B', 'Drill', TRUE, 'Lightning Rod');
INSERT INTO Pokemon VALUES(113, 'Chansey', 'F', 'Egg', TRUE, 'Serence Grace');
INSERT INTO Pokemon VALUES(114, 'Tangela', 'B', 'Vine', FALSE, 'Leaf Guard');
INSERT INTO Pokemon VALUES(115, 'Kangaskhan', 'F', 'Parent', FALSE, 'Scrappy');
INSERT INTO Pokemon VALUES(116, 'Horsea', 'B', 'Dragon', FALSE, 'Sniper');
INSERT INTO Pokemon VALUES(117, 'Seadra', 'B', 'Dragon', TRUE, 'Poison Point');
INSERT INTO Pokemon VALUES(118, 'Goldeen', 'B', 'Goldfish', FALSE, 'Water Veil');
INSERT INTO Pokemon VALUES(119, 'Seaking', 'B', 'Goldfish', TRUE, 'Swift Swim');
INSERT INTO Pokemon VALUES(120, 'Staryu', 'U', 'Star Shape', FALSE, 'Nature Cure');
INSERT INTO Pokemon VALUES(121, 'Starmie', 'U', 'Mysterious', TRUE, 'Illuminate');
INSERT INTO Pokemon VALUES(122, 'Mr.Mime', 'B', 'Barrier', TRUE, 'Filter');
INSERT INTO Pokemon VALUES(123, 'Scyther', 'B', 'Mantis', FALSE, 'Technician');
INSERT INTO Pokemon VALUES(124, 'Jynx', 'F', 'Human Shape', TRUE, 'Forewarn');
INSERT INTO Pokemon VALUES(125, 'Electrabuzz', 'B', 'Electric', TRUE, 'Static');
INSERT INTO Pokemon VALUES(126, 'Magmar', 'B', 'Spitfire', TRUE, 'Flame Body');
INSERT INTO Pokemon VALUES(127, 'Pinsir', 'B', 'Stag Beetle', FALSE, 'Nature Cure');
INSERT INTO Pokemon VALUES(128, 'Tauros', 'M', 'Wild Bull', FALSE, 'Anger Point');
INSERT INTO Pokemon VALUES(129, 'Magikarp', 'B', 'Fish', FALSE, 'Swift Swim');
INSERT INTO Pokemon VALUES(130, 'Gyarados', 'B', 'Atrocious', TRUE, 'Intimidate');
INSERT INTO Pokemon VALUES(131, 'Lapras', 'B', 'Transport', FALSE, 'Shell Armor');
INSERT INTO Pokemon VALUES(132, 'Ditto', 'U', 'Transform', FALSE,'Limber');
INSERT INTO Pokemon VALUES(133, 'Eevee', 'B', 'Evolution', FALSE, 'Adaptability');
INSERT INTO Pokemon VALUES(134, 'Vaporeon', 'B', 'Bubble Jet', TRUE, 'Water Absorb');
INSERT INTO Pokemon VALUES(137, 'Porygon', 'U', 'Virtual', FALSE, 'Download');
INSERT INTO Pokemon VALUES(138, 'Omanyte', 'B', 'Spiral', FALSE, 'Shell Armor');
INSERT INTO Pokemon VALUES(139, 'Omastar', 'B', 'Spiral', TRUE, 'Swift Armor');
INSERT INTO Pokemon VALUES(140, 'Kabuto', 'B', 'Shellfish', TRUE, 'Swift Swim');
INSERT INTO Pokemon VALUES(141, 'Kabutops', 'B', 'Shellfish', TRUE, 'Battle Armor');
INSERT INTO Pokemon VALUES(142, 'Aerodactyl', 'B', 'Fossil', FALSE, 'Pressure');
INSERT INTO Pokemon VALUES(143, 'Snorlax', 'B', 'Sleeping', TRUE, 'Thick Fat');
INSERT INTO Pokemon VALUES(144, 'Articuno', 'U', 'Freeze', FALSE, 'Pressure');
INSERT INTO Pokemon VALUES(145, 'Zapdos', 'U', 'Electric', FALSE, 'Pressure');
INSERT INTO Pokemon VALUES(146, 'Moltres', 'U', 'Flame', FALSE, 'Pressure');
INSERT INTO Pokemon VALUES(147, 'Dratini', 'B', 'Dragon', FALSE, 'Shed Skin');
INSERT INTO Pokemon VALUES(148, 'Dragonair', 'B', 'Dragon', TRUE, 'Shed Skin');
INSERT INTO Pokemon VALUES(149, 'Dragonite', 'B', 'Dragon', TRUE, 'Inner Focus');
INSERT INTO Pokemon VALUES(150, 'Mewtwo', 'U', 'Genetic', FALSE, 'Pressure');
INSERT INTO Pokemon VALUES(151, 'Mew', 'U', 'New Species', FALSE, 'Synchronize');
INSERT INTO Pokemon VALUES(165, 'Ledyba', 'B', 'Five Star', FALSE, 'Swarm');
INSERT INTO Pokemon VALUES(166, 'Ledian', 'B', 'Five Star', TRUE, 'Swarm');
INSERT INTO Pokemon VALUES(169, 'Crobat', 'B', 'Bat', TRUE, 'Infiltrator');
INSERT INTO Pokemon VALUES(172, 'Pichu', 'B', 'Tiny Mouse', FALSE, 'Static');
INSERT INTO Pokemon VALUES(173, 'Cleffa', 'B', 'Star Shape', FALSE, 'Friend Guard');
INSERT INTO Pokemon VALUES(174, 'Igglypuff', 'B', 'Ballon', FALSE, 'Friend Guard');
INSERT INTO Pokemon VALUES(191, 'Sunkern', 'B', 'Seed', FALSE, 'Solar Power');
INSERT INTO Pokemon VALUES(192, 'Sunflora', 'B', 'Sun', TRUE, 'Solar Power');
INSERT INTO Pokemon VALUES(202, 'Wobbuffet', 'B', 'Patient', TRUE, 'Shadow Tag');
INSERT INTO Pokemon VALUES(203, 'Girafarig', 'B', 'Long Neck', FALSE, 'Inner Focus');
INSERT INTO Pokemon VALUES(208, 'Steelix', 'B', 'Iron Snake', TRUE, 'Sturdy');
INSERT INTO Pokemon VALUES(212, 'Scizor', 'B', 'Pincer', TRUE, 'Swarm');
INSERT INTO Pokemon VALUES(214, 'Heracross', 'B', 'Single Horn', FALSE, 'Guts');
INSERT INTO Pokemon VALUES(215, 'Sneasel', 'B', 'Sharp Claw', FALSE, 'Keen Eye');
INSERT INTO Pokemon VALUES(227, 'Skarmory', 'B', 'Armor Bird', FALSE, 'Sturdy');
INSERT INTO Pokemon VALUES(228, 'Houndour', 'B', 'Dark', FALSE, 'Flash Fire');
INSERT INTO Pokemon VALUES(229, 'Houndoom', 'B', 'Dark', TRUE, 'Flash Fire');
INSERT INTO Pokemon VALUES(230, 'Kingdra', 'B', 'Dragon', TRUE, 'Swift Swim');
INSERT INTO Pokemon VALUES(233, 'Porygon2', 'U', 'Virtual', TRUE, 'Download');
INSERT INTO Pokemon VALUES(236, 'Tyrogue', 'M', 'Scuffle', FALSE, 'Steadfast');
INSERT INTO Pokemon VALUES(238, 'Smoochum', 'F', 'Kiss', FALSE, 'Forewarn');
INSERT INTO Pokemon VALUES(239, 'Elekid', 'B', 'Electric', FALSE, 'Static');
INSERT INTO Pokemon VALUES(240, 'Magby', 'B', 'Live Coal', FALSE, 'Flame Body');
INSERT INTO Pokemon VALUES(241, 'Miltank', 'F', 'Milk Cow', FALSE, 'Scrappy');
INSERT INTO Pokemon VALUES(242, 'Blissey', 'F', 'Happiness', TRUE, 'Natural Cure');
INSERT INTO Pokemon VALUES(258, 'Mudkip', 'B', 'Mud Fish', FALSE, 'Torrent');
INSERT INTO Pokemon VALUES(259, 'Marshtomp', 'B', 'Mud Fish', TRUE, 'Torrent');
INSERT INTO Pokemon VALUES(260, 'Swampert', 'B', 'Mud Fish', TRUE, 'Torrent');
INSERT INTO Pokemon VALUES(265, 'Wurmple', 'B', 'Worm', FALSE, 'Shield Dust');
INSERT INTO Pokemon VALUES(266, 'Silcoon', 'B', 'Cocoon', TRUE, 'Shed Skin');
INSERT INTO Pokemon VALUES(267, 'Beautifly', 'B', 'Butterfly', TRUE, 'Swarm');
INSERT INTO Pokemon VALUES(273, 'Seedot', 'B', 'Accorn', FALSE, 'Chlorophyll');
INSERT INTO Pokemon VALUES(274, 'Nuzleaf', 'B', 'Wily', TRUE, 'Early Bird');
INSERT INTO Pokemon VALUES(275, 'Shiftry', 'B', 'Wicked', TRUE, 'Early Bird');
INSERT INTO Pokemon VALUES(278, 'Wingull', 'B', 'Seagull', FALSE, 'Keen Eye');
INSERT INTO Pokemon VALUES(279, 'Pelipper', 'B', 'Water Bird', TRUE, 'Keen Eye');
INSERT INTO Pokemon VALUES(287, 'Slakoth', 'B', 'Slacker', FALSE, 'Truant');
INSERT INTO Pokemon VALUES(288, 'Vigoroth', 'B', 'Wild Monkey', TRUE, 'Vital Spirit');
INSERT INTO Pokemon VALUES(289, 'Slaking', 'B', 'Lazy', TRUE, 'Truant');
INSERT INTO Pokemon VALUES(300, 'Skitty', 'B', 'Kitten', FALSE, 'Normalize');
INSERT INTO Pokemon VALUES(301, 'Delcatty', 'B', 'Prim', TRUE, 'Cute Charm');
INSERT INTO Pokemon VALUES(302, 'Sableye', 'B', 'Darkness', FALSE, 'Keen Eye');
INSERT INTO Pokemon VALUES(311, 'Plusle', 'B', 'Cheering', FALSE, 'Plus');
INSERT INTO Pokemon VALUES(314, 'Illumise', 'F', 'Firefly', FALSE, 'Tinted Lens');
INSERT INTO Pokemon VALUES(320, 'Wailmer', 'B', 'Ball Whale', FALSE, 'Water Veil');
INSERT INTO Pokemon VALUES(321, 'Wailord', 'B', 'Float Whale', TRUE, 'Water Veil');
INSERT INTO Pokemon VALUES(324, 'Torkoal', 'B', 'Coal', FALSE, 'White Smoke');
INSERT INTO Pokemon VALUES(327, 'Spinda', 'B', 'Spot Panda', FALSE, 'Tangled Feet');
INSERT INTO Pokemon VALUES(333, 'Swablu', 'B', 'Cotton Bird', FALSE, 'Nature Cure');
INSERT INTO Pokemon VALUES(334, 'Altaria', 'B', 'Humming', TRUE, 'Nature Cure');
INSERT INTO Pokemon VALUES(337, 'Lunatone', 'U', 'Meteorite', FALSE, 'Levitate');
INSERT INTO Pokemon VALUES(347, 'Anorith', 'B', 'Old Shrimp', FALSE, 'Battle Armor');
INSERT INTO Pokemon VALUES(348, 'Armaldo', 'B', 'Plate Armor', TRUE, 'Battle Armor');
INSERT INTO Pokemon VALUES(349, 'Feebas', 'B', 'Fish', FALSE, 'Swift Swim');
INSERT INTO Pokemon VALUES(350, 'Milotic', 'B', 'Tender', TRUE, 'Marvel Scale');
INSERT INTO Pokemon VALUES(360, 'Wynaut',	'B', 'Bright', FALSE, 'Shadow Tag');
INSERT INTO Pokemon VALUES(387, 'Turtwig', 'B', 'Tiny Leaf', FALSE, 'Overgrow');
INSERT INTO Pokemon VALUES(388, 'Grotle', 'B', 'Grove', TRUE, 'Overgrow');
INSERT INTO Pokemon VALUES(389, 'Torterra', 'B', 'Continent', TRUE, 'Overgrow');
INSERT INTO Pokemon VALUES(390, 'Chimchar', 'B', 'Chimp', FALSE, 'Blaze');
INSERT INTO Pokemon VALUES(391, 'Monferno', 'B', 'Playful', TRUE, 'Blaze');
INSERT INTO Pokemon VALUES(392, 'Infernape', 'B', 'Flame', TRUE, 'Blaze');
INSERT INTO Pokemon VALUES(431, 'Glameow', 'B', 'Catty', FALSE, 'Limber');
INSERT INTO Pokemon VALUES(432, 'Purugle', 'B', 'Tiger Cat', TRUE, 'Thick Fat');
INSERT INTO Pokemon VALUES(439, 'Mime Jr.', 'B', 'Mime', FALSE, 'Filter');
INSERT INTO Pokemon VALUES(440, 'Happiny', 'F', 'Playhouse', FALSE, 'Serene Grace');
INSERT INTO Pokemon VALUES(446, 'Munchlax', 'B', 'Eater', FALSE, 'Thick Fat');
INSERT INTO Pokemon VALUES(447, 'Riolu', 'B', 'Emanation', FALSE, 'Steadfast');
INSERT INTO Pokemon VALUES(448, 'Lucario', 'B', 'Aura', TRUE, 'Inner Focus');
INSERT INTO Pokemon VALUES(461, 'Weavile', 'B', 'Sharp Claw', TRUE, 'Pressure');
INSERT INTO Pokemon VALUES(462, 'Magnezone', 'U', 'Magnet Area', TRUE, 'Magnet Pull');
INSERT INTO Pokemon VALUES(463, 'Lickilicky', 'B', 'Licking', TRUE, 'Oblivious');
INSERT INTO Pokemon VALUES(464, 'Rhyperior', 'B', 'Drill', TRUE, 'Solid Rock');
INSERT INTO Pokemon VALUES(465, 'Tangrowth', 'B', 'Vine', TRUE, 'Leaf Guard');
INSERT INTO Pokemon VALUES(466, 'Electivire', 'B', 'Thunderbolt', TRUE, 'Motor Drive');
INSERT INTO Pokemon VALUES(467, 'Magmortar', 'B', 'Blast', TRUE, 'Flame Body');
INSERT INTO Pokemon VALUES(501, 'Oshawott', 'B', 'Sea Otter', FALSE, 'Torrent');
INSERT INTO Pokemon VALUES(502, 'Dewott', 'B', 'Discipline', TRUE, 'Torrent');
INSERT INTO Pokemon VALUES(503, 'Samurott', 'B', 'Formidable', TRUE, 'Torrent');
INSERT INTO Pokemon VALUES(504, 'Patrat', 'B', 'Scout', FALSE, 'Run Away');
INSERT INTO Pokemon VALUES(505, 'Watchog', 'B', 'Lookout', TRUE, 'Illuminate');
INSERT INTO Pokemon VALUES(548, 'Petilil', 'F', 'Bulb', FALSE, 'Chlorophyll');
INSERT INTO Pokemon VALUES(549, 'Lilligant', 'F', 'Flowering', TRUE, 'Chlorophyll');
INSERT INTO Pokemon VALUES(561, 'Sigilyph', 'B', 'Avianoid', FALSE, 'Magic Guard');
INSERT INTO Pokemon VALUES(580, 'Ducklett', 'B', 'Water Bird', FALSE, 'Keen Eye');
INSERT INTO Pokemon VALUES(581, 'Swanna', 'B', 'White Bird', TRUE, 'Big Pecks');
INSERT INTO Pokemon VALUES(587, 'Emolga', 'B', 'Sky Squirrel', FALSE, 'Static');
INSERT INTO Pokemon VALUES(615, 'Cryogonal', 'U', 'Crystallizing', FALSE, 'Levitate');
INSERT INTO Pokemon VALUES(621, 'Druddigon', 'B', 'Cave', FALSE,'Rough Skin');
INSERT INTO Pokemon VALUES(650, 'Chespin', 'B', 'Spiny Nut', FALSE, 'Overgrow');
INSERT INTO Pokemon VALUES(651, 'Quilladin', 'B', 'Spiny Armor', TRUE, 'Overgrow');
INSERT INTO Pokemon VALUES(652, 'Chesnaught', 'B', 'Spiny Armor', TRUE, 'Overgrow');
INSERT INTO Pokemon VALUES(664, 'Scatterbug', 'B', 'Scatterdust', FALSE, 'Shield Dust');
INSERT INTO Pokemon VALUES(665, 'Spewpa', 'B', 'Scatterdust', TRUE, 'Shed Skin');
INSERT INTO Pokemon VALUES(666, 'Vivillon', 'B', 'Scale', TRUE, 'Compound Eyes');
INSERT INTO Pokemon VALUES(698, 'Amaura', 'B', 'Tundra', FALSE, 'Refrigerate');
INSERT INTO Pokemon VALUES(699, 'Aurorus', 'B', 'Tundra', TRUE, 'Refrigerate');
