INSERT INTO Evolution VALUES(1,' Bulbasaur',16,' Normal',' Egg',' Venusaur');
INSERT INTO Evolution VALUES(2,' Ivysaur',32,' Normal',' Bulbasaur',' Venusaur');
INSERT INTO Evolution VALUES(3,' Venusaur',NULL,NULL,' Ivysaur',NULL);
INSERT INTO Evolution VALUES(4,' Charmander',16,' Normal',' Egg',' Charmeleon');
INSERT INTO Evolution VALUES(5,' Charmeleon',36,' Normal',' Charmander',' Charizard');
INSERT INTO Evolution VALUES(6,' Charizard',NULL,NULL,' Charmeleon',NULL);
INSERT INTO Evolution VALUES(7,' Squirtle',16,' Normal',' Egg',' Wartotle');
INSERT INTO Evolution VALUES(8,' Wartotle',36,' Normal',' Squirtle',' Blastoise');
INSERT INTO Evolution VALUES(9,' Blastoise',NULL,NULL,' Wartotle',NULL);
INSERT INTO Evolution VALUES(10,' Caterpie',7,' Normal',' Egg',' Metapod');
INSERT INTO Evolution VALUES(11,' Metapod',10,' Normal',' Caterpie',' Butterfree');
INSERT INTO Evolution VALUES(12,' Butterfree',NULL,NULL,' Metapod',NULL);
INSERT INTO Evolution VALUES(13,' Weedle',7,' Normal',' Egg',' Kakuna');
INSERT INTO Evolution VALUES(14,' Kakuna',10,' Normal',' Caterpie',' Beedrill');
INSERT INTO Evolution VALUES(15,' Beedrill',NULL,NULL,' Kakuna',NULL);
INSERT INTO Evolution VALUES(16,' Pidgey',18,' Normal',' Egg',' Pidgeotto');
INSERT INTO Evolution VALUES(17,' Pidgeotto',36,' Normal',' Pidgey',' Pidgeot');
INSERT INTO Evolution VALUES(18,' Pidgeot',NULL,NULL,' Pidgeotto',NULL);
INSERT INTO Evolution VALUES(19,' Rattata',20,' Normal',' Egg',' Raticate');
INSERT INTO Evolution VALUES(20,' Raticate',NULL,NULL,'Rattata',NULL);
INSERT INTO Evolution VALUES(21,'Spearow',20,'Normal','Egg','Fearow');
INSERT INTO Evolution VALUES(22,'Fearow',NULL,NULL,'Spearow',NULL);
INSERT INTO Evolution VALUES(23,'Ekans',22,'Normal','Egg','Arbok');
INSERT INTO Evolution VALUES(24,'Arbok',NULL,NULL,' Ekans',NULL);
INSERT INTO Evolution VALUES(25,'Pikachu',NULL,'Thunderstone','Pichu','Raichu');
INSERT INTO Evolution VALUES(26,'Raichu',NULL,NULL,'Pikachu',NULL);
INSERT INTO Evolution VALUES(27,'Sandshrew',22,'Normal','Egg','Sandslah');
INSERT INTO Evolution VALUES(28,'Sandslash',NULL,NULL,'Sandshrew',NULL);
INSERT INTO Evolution VALUES(29,' Nidoran',16,'Normal','EggL','Nidorina');
INSERT INTO Evolution VALUES(30,'Nidorina',NULL,' Moon Stone',' Nidoran',' Nidoqueen ');
INSERT INTO Evolution VALUES(31,' Nidoqueen',NULL,NULL,' Nidorina',NULL);
INSERT INTO Evolution VALUES(32,' Nidoran',16,' Normal',' Egg',' Nidorino');
INSERT INTO Evolution VALUES(33,' Nidorino',NULL,' Moon Stone',' Nidoran',' Nidoqueen');
INSERT INTO Evolution VALUES(34,' Nidoking',NULL,NULL,' Nidorino',NULL);
INSERT INTO Evolution VALUES(35,' Clefairy',NULL,' Moon Stone',' Cleffa',' Clefable');
INSERT INTO Evolution VALUES(36,' Clefable',NULL,NULL,' Clefairy',NULL);
INSERT INTO Evolution VALUES(37,' Vulpix',NULL,'Moon Stone','Egg','Ninetails');
INSERT INTO Evolution VALUES(38,' Ninetails',NULL,NULL,' Vulpix',NULL);
INSERT INTO Evolution VALUES(39,' Jigglypuff',NULL,' Moon Stone',' Igglybuff',' Wigglytuff');
INSERT INTO Evolution VALUES(40,' Wigglytuff',NULL,NULL,' Jigglypuff',NULL);
INSERT INTO Evolution VALUES(41,' Zubat',22,'Normal',' Egg',' Golbat');
INSERT INTO Evolution VALUES(42,' Golbat',NULL,' Friendship',' Zubat',' Crobat');
INSERT INTO Evolution VALUES(43,' Oddish',21,' Normal',' Egg',' Gloom');
INSERT INTO Evolution VALUES(44,' Gloom',NULL,' Leaf Stone',' Oddish',' Vileplume');
INSERT INTO Evolution VALUES(45,' Vileplume',NULL,NULL,' Gloom ',NULL);
INSERT INTO Evolution VALUES(46,' Paras',24,'Normal','Egg','Parasect');
INSERT INTO Evolution VALUES(47,'Parasect',NULL,NULL,'Paras',NULL);
INSERT INTO Evolution VALUES(48,' Venonat',31,'Normal','Egg','Venomoth');
INSERT INTO Evolution VALUES(49,' Venomoth',NULL,NULL,' Venonat',NULL);
INSERT INTO Evolution VALUES(50,' Diglett',26,' Normal','Egg',' Dugtrio');
INSERT INTO Evolution VALUES(51,' Dugtrio',NULL,'NULL Diglett',NULL,);
INSERT INTO Evolution VALUES(52,'Meowth',28,'Normal','Egg','Persian');
INSERT INTO Evolution VALUES(53,' Persian',NULL,NULL,'Meowth',NULL);
INSERT INTO Evolution VALUES(54,' Psyduck',33,' Normal',' Egg','Golduck');
INSERT INTO Evolution VALUES(55,' Golduck',NULL,NULL,' Psyduck',NULL);
INSERT INTO Evolution VALUES(56,' Mankey',28,' Normal',' Egg',' Primeape');
INSERT INTO Evolution VALUES(57,'Primeape',NULL,NULL,'Mankey',NULL);
INSERT INTO Evolution VALUES(58,' Growlithe',NULL,' Fire Stone',' Egg',' Arcanine');
INSERT INTO Evolution VALUES(59,' Arcanine',NULL,NULL,' Growlithe',NULL);
INSERT INTO Evolution VALUES(60,' Poliwag',25,' Normal',' Egg',' Poliwhirl');
INSERT INTO Evolution VALUES(61,' Poliwhirl',NULL,' Water Stone',' Poliwag',' Poliwhirl');
INSERT INTO Evolution VALUES(62,' Poliwrath',NULL,NULL,' Poliwhirl',NULL);
INSERT INTO Evolution VALUES(63,' Abra',16,' Normal',' Egg',' Kadabra');
INSERT INTO Evolution VALUES(64,' Kadabra',NULL,' Trade',' Abra',' Alakazam');
INSERT INTO Evolution VALUES(65,' Alakazam',NULL,NULL,' Kadabra',NULL);
INSERT INTO Evolution VALUES(66,' Machop',28,' Normal',' Egg',' Machoke');
INSERT INTO Evolution VALUES(67,' Machoke',NULL,' Trade',' Machop',' Machamp');
INSERT INTO Evolution VALUES(68,' Machamp',NULL,NULL,' Machop',NULL);
INSERT INTO Evolution VALUES(69,' Bellsprout',21,' Normal',' Egg',' Weepinbell');
INSERT INTO Evolution VALUES(70,' Weepinbell',NULL,' Leaf Stone',' Bellsprout',' Victreebel');
INSERT INTO Evolution VALUES(71,' Victreebel',NULL,NULL,' Weepinbell',NULL);
INSERT INTO Evolution VALUES(72,' Tentacool',30,' Normal',' Egg',' Tentacruel');
INSERT INTO Evolution VALUES(73,' Tentacruel',NULL,NULL,' Tenacool',NULL);
INSERT INTO Evolution VALUES(74,' Geodude',25,' Normal',' Egg',' Graveler');
INSERT INTO Evolution VALUES(75,' Graveler',NULL,' Trade',' Geodude',' Golem ');
INSERT INTO Evolution VALUES(76,' Golem',NULL,NULL,' Graveler',NULL);
INSERT INTO Evolution VALUES(77,' Ponyta',40,' Normal','Egg',' Rapidash');
INSERT INTO Evolution VALUES(78,' Rapidash',NULL,NULL,'Ponyta',NULL);
INSERT INTO Evolution VALUES(79,' Slowpoke',37,' Normal',' Egg',' Slowbro');
INSERT INTO Evolution VALUES(80,' Slowbro',NULL,NULL,'Slowbro',NULL);
INSERT INTO Evolution VALUES(81,' Magnemite',30,'Normal','Egg','Magneton');
INSERT INTO Evolution VALUES(82,'Magneton',NULL,' Chargestone Cave','Magnemite','Magnezone');
INSERT INTO Evolution VALUES(83,'Farfetchd',NULL,NULL,'Egg',NULL);
INSERT INTO Evolution VALUES(84,' Doduo',31,'Normal','Egg','Dodrio');
INSERT INTO Evolution VALUES(85,' Dodrio',NULL,NULL,'Doduo',NULL);
INSERT INTO Evolution VALUES(86,' Seel',34,' Normal',' Egg',' Dewgong');
INSERT INTO Evolution VALUES(87,' Dewgong',NULL,NULL,' Seel',NULL);
INSERT INTO Evolution VALUES(88,' Grimer',38,' Normal',' Egg',' Muk');
INSERT INTO Evolution VALUES(89,' Muk',NULL,NULL,' Grimer',NULL);
INSERT INTO Evolution VALUES(90,' Shellder',NULL,' Water Stone',' Egg',' Cloyster');
INSERT INTO Evolution VALUES(91,' Cloyster',NULL,NULL,' Shellder',NULL);
INSERT INTO Evolution VALUES(92,' Gastly',22,' Normal',' Egg',' Hunter');
INSERT INTO Evolution VALUES(93,' Hunter',NULL,' Trade',' Gastly',' Gengar');
INSERT INTO Evolution VALUES(94,' Gengar',NULL,NULL,'Hunter',NULL);
INSERT INTO Evolution VALUES(95,' Onix',NULL,' Trade holding Metal Coat',' Egg','Steelix');
INSERT INTO Evolution VALUES(96,' Drowzee',26,' Normal',' Egg',' Hypno');
INSERT INTO Evolution VALUES(97,' Hypno',NULL,NULL,'Drowzee',NULL);
INSERT INTO Evolution VALUES(98,' Krabby',28,'Normal','Egg','Kingler');
INSERT INTO Evolution VALUES(99,'Kingler',NULL,NULL,'Krabby',NULL);
INSERT INTO Evolution VALUES(100,' Voltorb',30,' Normal',' Egg','Electrode');
INSERT INTO Evolution VALUES(101,' Electrode',NULL,NULL,' Voltorb',NULL);
INSERT INTO Evolution VALUES(102,' Exeggcute',NULL,' Leaf Stone',' Egg',' Exeggutor');
INSERT INTO Evolution VALUES(103,' Exeggutor',NULL,NULL,'Exeggcute',NULL);
INSERT INTO Evolution VALUES(104,' Cubone',28,' Normal',' Egg',' Marowak');
INSERT INTO Evolution VALUES(105,' Marowak',NULL,NULL,'Cubone',NULL);
INSERT INTO Evolution VALUES(106,' Hitmonlee',NULL,NULL,' Tyrogue',NULL);
INSERT INTO Evolution VALUES(107,' Hitmonchan',NULL,NULL,' Tyrogue',NULL);
INSERT INTO Evolution VALUES(108,' Lickitung',NULL,'Level up knowing Rollout',' Egg',' Lickilicky');
INSERT INTO Evolution VALUES(109,' Koffing',35,' Normal',' Egg',' Weezing');
INSERT INTO Evolution VALUES(110,' Weezing',NULL,'NULL Koffing',NULL,);
INSERT INTO Evolution VALUES(111,' Rhyhorn',42,'Normal',' Egg',' Rhydon');
INSERT INTO Evolution VALUES(112,' Rhydon',NULL,' Trade holding Protector',' Rhyhorn',' Rhyperior');
INSERT INTO Evolution VALUES(113,' Chansey',NULL,' Friendship',' Happiny',' Blissey');
INSERT INTO Evolution VALUES(114,' Tangela',NULL,' Level up knowing Ancient Power',' Egg',' Tangrowth');
INSERT INTO Evolution VALUES(115,' Kangaskhan',NULL,NULL,'Egg',NULL);
INSERT INTO Evolution VALUES(116,' Horsea',32,' Normal',' Egg',' Seadra');
INSERT INTO Evolution VALUES(117,' Seadra',NULL,' Trade holding Dragon Scale',' Horsea',' Kingdra');
INSERT INTO Evolution VALUES(118,' Goldeen',33,' Normal',' Egg',' Seaking');
INSERT INTO Evolution VALUES(119,' Seaking',NULL,NULL,'Goldeen',NULL);
INSERT INTO Evolution VALUES(120,' Staryu',NULL,' Water Stone',' Egg',' Starmie');
INSERT INTO Evolution VALUES(121,' Starmie',NULL,NULL,' Staryu',NULL);
INSERT INTO Evolution VALUES(122,' Mr.Mime',NULL,NULL,' Mime Jr. ',NULL);
INSERT INTO Evolution VALUES(123,' Scyther',NULL,' Trade holding Metal Coat',' Egg','Scizor');
INSERT INTO Evolution VALUES(124,' Jynx',NULL,NULL,' Smoochum',NULL);
INSERT INTO Evolution VALUES(125,' Electabuzz',NULL,' Trade holding Electirizer',' Elekid',' Electivire');
INSERT INTO Evolution VALUES(126,' Magmar',NULL,'Trade holding Magmarizer',' Magby',' Magmortar');
INSERT INTO Evolution VALUES(127,' Pinsir',NULL,NULL,' Egg',NULL);
INSERT INTO Evolution VALUES(128,' Tauros',NULL,NULL,'Egg',NULL);
INSERT INTO Evolution VALUES(129,' Magikarp',20,' Normal',' Egg',' Gyarados');
INSERT INTO Evolution VALUES(130,' Gyarados',NULL,NULL,'Magikarp',NULL);
INSERT INTO Evolution VALUES(131,' Lapras',NULL,NULL,'Egg',NULL);
INSERT INTO Evolution VALUES(132,' Ditto',NULL,NULL,'Egg',NULL);
INSERT INTO Evolution VALUES(133,' Eevee',NULL,'Water Stone',' Egg',' Vaporeon');
INSERT INTO Evolution VALUES(134,' Vaporeon',NULL,NULL,'Eevee',NULL);
INSERT INTO Evolution VALUES(137,' Porygon',NULL,' Trade holding Up-Grade',' Unknown',' Porygon2);
INSERT INTO Evolution VALUES(138,' Omanyte',40,' Normal ',' Fossil',' Omastar');
INSERT INTO Evolution VALUES(139,' Omastar',NULL,NULL,'Omanyte',NULL);
INSERT INTO Evolution VALUES(140,' Kabuto',40,' Normal',' Fossil',' Kabutops');
INSERT INTO Evolution VALUES(141,' Kabutops',NULL,NULL,'Kabuto',NULL);
INSERT INTO Evolution VALUES(142,' Aerodactyl',NULL,NULL,'Fossil',NULL);
INSERT INTO Evolution VALUES(143,' Snorlax',NULL,NULL,'Munchlax',NULL);
INSERT INTO Evolution VALUES(144,' Articuno',NULL,NULL,'Unknown',NULL);
INSERT INTO Evolution VALUES(145,' Zapdos',NULL,NULL,'Unknown',NULL);
INSERT INTO Evolution VALUES(146,' Moltres',NULL,NULL,'Unknown',NULL);
INSERT INTO Evolution VALUES(147,' Dratini',30,' Normal',' Egg',' Dragonair');
INSERT INTO Evolution VALUES(148,' Dragonair',55,' Normal',' Dratini',' Dragonite');
INSERT INTO Evolution VALUES(149,' Dragonite',NULL,NULL,'Dragonair',NULL);
INSERT INTO Evolution VALUES(150,' Mewtwo',NULL,NULL,'Unknown',NULL);
INSERT INTO Evolution VALUES(151,' Mew',NULL,NULL,'Unknown',NULL);
INSERT INTO Evolution VALUES(165,' Ledyba',18,' Normal',' Egg',' Ledian');
INSERT INTO Evolution VALUES(166,' Ledian',NULL,NULL,'Ledyba',NULL);
INSERT INTO Evolution VALUES(169,' Crobat',NULL,NULL,'Golbat',NULL);
INSERT INTO Evolution VALUES(172,'Pichu',NULL,'Friendship','Egg','Pikachu');
INSERT INTO Evolution VALUES(173,' Cleffa',NULL,'Friendship','Egg','Clefairy');
INSERT INTO Evolution VALUES(174,' Igglypuff',NULL,' Friendship',' Egg',' Jigglypuff');
INSERT INTO Evolution VALUES(191,' Sunkern',NULL,' Sun Stone',' Egg',' Sunflora');
INSERT INTO Evolution VALUES(192,' Sunflora',NULL,NULL,'Sunkern',NULL);
INSERT INTO Evolution VALUES(202,' Wobbuffet',NULL,NULL,' Wynaut',NULL);
INSERT INTO Evolution VALUES(203,' Girafarig',NULL,NULL,'Egg',NULL);
INSERT INTO Evolution VALUES(208,' Steelix',NULL,NULL,'Onix',NULL);
INSERT INTO Evolution VALUES(212,' Scizor',NULL,NULL,'Scyther',NULL);
INSERT INTO Evolution VALUES(214,' Heracross',NULL,NULL,'Egg',NULL);
INSERT INTO Evolution VALUES(215,' Sneasel',NULL,' Level up holding Razor Claw',' Egg','Weaville');
INSERT INTO Evolution VALUES(227,' Skarmory',NULL,NULL,'Egg',NULL);
INSERT INTO Evolution VALUES(228,' Houndour',24,' Normal',' Egg',' Houndoom');
INSERT INTO Evolution VALUES(229,' Houndoom',NULL,NULL,'Houndour',NULL);
INSERT INTO Evolution VALUES(230,' Kingdra',NULL,NULL,'Seadra',NULL);
INSERT INTO Evolution VALUES(233,' Porygon2,NULL,' Trade with Dubious Disc',' Porygon',' Porygon-Z');
INSERT INTO Evolution VALUES(236,' Tyrogue',20,' Attack > Defense',' Egg','Hitmonlee');
INSERT INTO Evolution VALUES(238,' Smoochum',30,'Normal',' Egg',' Jynx');
INSERT INTO Evolution VALUES(239,' Elekid',30,'Normal',' Egg',' Electabuzz');
INSERT INTO Evolution VALUES(240,' Magby',30,' Normal',' Egg',' Magmar');
INSERT INTO Evolution VALUES(241,' Miltank',NULL,NULL,'Egg',NULL);
INSERT INTO Evolution VALUES(242,' Blissey',NULL,NULL,'Chansey',NULL);
INSERT INTO Evolution VALUES(258,' Mudkip',16,' Normal',' Egg',' Marshtomp');
INSERT INTO Evolution VALUES(259,' Marshtomp',36,' Normal',' Mudkip',' Swampert');
INSERT INTO Evolution VALUES(260,' Swampert',NULL,NULL,'Marshtomp',NULL);
INSERT INTO Evolution VALUES(265,'Wurmple',7,'Normal',' Egg',' silcoon');
INSERT INTO Evolution VALUES(266,'Silcoon',10,'Normal',' Wurmple','Beautifly');
INSERT INTO Evolution VALUES(267,' Beautifly',NULL,NULL,'Silcoon',NULL);
INSERT INTO Evolution VALUES(273,' Seedot',14,' Normal',' Egg',' Nuzleaf');
INSERT INTO Evolution VALUES(274,' Nuzleaf',NULL,' Leaf Stone',' Seedot',' Shiftry');
INSERT INTO Evolution VALUES(275,' Shiftry',NULL,NULL,'Nuzleaf',NULL);
INSERT INTO Evolution VALUES(278,' Wingull',25,' Normal',' Egg',' Pelipper');
INSERT INTO Evolution VALUES(279,' Pelipper',NULL,NULL,'Wingull',NULL);
INSERT INTO Evolution VALUES(287,' Slakoth',18,' Normal',' Egg',' Vigoroth');
INSERT INTO Evolution VALUES(288,' Vigoroth',36,' Normal',' Slakoth',' Slaking');
INSERT INTO Evolution VALUES(289,' Slaking',NULL,NULL,' Vigoroth',NULL);
INSERT INTO Evolution VALUES(300,' Skitty',NULL,' Moon Stone',' Egg',' Delcatty');
INSERT INTO Evolution VALUES(301,' Delcatty',NULL,NULL,'Skitty',NULL);
INSERT INTO Evolution VALUES(302,'Sableye',NULL,NULL,'Egg',NULL);
INSERT INTO Evolution VALUES(311,' Plusle',NULL,NULL,'Egg',NULL);
INSERT INTO Evolution VALUES(314,' Illumise',NULL,NULL,'Egg',NULL);
INSERT INTO Evolution VALUES(320,' Wailmer',40,' Normal',' Egg',' Wailord');
INSERT INTO Evolution VALUES(321,' Wailord',NULL,NULL,' Wailmer',NULL);
INSERT INTO Evolution VALUES(324,' Torkoal',NULL,NULL,' Egg',NULL);
INSERT INTO Evolution VALUES(327,' Spinda',NULL,NULL,' Egg',NULL);
INSERT INTO Evolution VALUES(333,' Swablu',35,' Normal',' Egg',' Altaria');
INSERT INTO Evolution VALUES(334,' Altaria',NULL,NULL,'Swablu',NULL);
INSERT INTO Evolution VALUES(337,' Lunatone',NULL,NULL,' Unknown',NULL);
INSERT INTO Evolution VALUES(347,' Anorith',40,' Normal',' Fossil',' Armaldo');
INSERT INTO Evolution VALUES(348,' Armaldo',NULL,NULL,'Anorith',NULL);
INSERT INTO Evolution VALUES(349,' Feebas',NULL,' Level up with High Beauty','Egg',' Milotic');
INSERT INTO Evolution VALUES(350,' Milotic',NULL,NULL,' Feebas',NULL);
INSERT INTO Evolution VALUES(360,' Wynaut',15,' Normal',' Egg',' Wobbuffet');
INSERT INTO Evolution VALUES(387,' Turtwig',18,' Normal',' Egg',' Grottle');
INSERT INTO Evolution VALUES(388,' Grottle',32,' Normal',' Turtwig',' Torterra');
INSERT INTO Evolution VALUES(389,' Torterra',NULL,NULL,'Grottle',NULL);
INSERT INTO Evolution VALUES(390,' Chimchar',14,' Normal',' Egg',' Monferno');
INSERT INTO Evolution VALUES(391,' Monferno',36,' Normal',' Chimchar',' Infernape');
INSERT INTO Evolution VALUES(392,' Infernape',NULL,NULL,' Monferno',NULL);
INSERT INTO Evolution VALUES(431,' Glameow',38,' Normal',' Egg',' Purugly');
INSERT INTO Evolution VALUES(432,' Purugly',NULL,NULL,'Glameow',NULL);
INSERT INTO Evolution VALUES(439,' Mime Jr. ',NULL,' Level up knowing Mimic',' Egg',' Mr.Mime');
INSERT INTO Evolution VALUES(440,' Happiny',NULL,' Level up holding Oval Stone(Daytime)',' Egg',' Chansey');
INSERT INTO Evolution VALUES(446,' Munchlax',NULL,'Friendship','Egg','Snorlax');
INSERT INTO Evolution VALUES(447,' Riolu',NULL,' Friendship(Daytime)',' Egg',' Lucario');
INSERT INTO Evolution VALUES(448,' Lucario',NULL,NULL,' Riolu',NULL);
INSERT INTO Evolution VALUES(461,' Weavile',NULL,NULL,'Sneasel',NULL);
INSERT INTO Evolution VALUES(462,' Magnezone',NULL,NULL,'Magneton',NULL);
INSERT INTO Evolution VALUES(463,' Lickilicky',NULL,NULL,'Lickitung',NULL);
INSERT INTO Evolution VALUES(464,' Rhyperior',NULL,NULL,'Rhydon',NULL);
INSERT INTO Evolution VALUES(465,' Tangrowth',NULL,NULL,'Tangela',NULL);
INSERT INTO Evolution VALUES(466,' Electivire',NULL,NULL,' Electabuzz',NULL);
INSERT INTO Evolution VALUES(467,' Magmortar',NULL,NULL,'Magmar',NULL);
INSERT INTO Evolution VALUES(474,' Porygon-Z',NULL,NULL,'Porygon2,NULL);
INSERT INTO Evolution VALUES(501,'Oshawott',17,' Normal',' Egg',' Dewott');
INSERT INTO Evolution VALUES(502,' Dewott',36,' Normal',' Oshawott',' Samurott');
INSERT INTO Evolution VALUES(503,'Samurott',NULL,NULL,'Dewott',NULL);
INSERT INTO Evolution VALUES(504,' Patrat',20,'Normal','Egg',' Watchog');
INSERT INTO Evolution VALUES(505,' Watchog',NULL,NULL,'Patrat',NULL);
INSERT INTO Evolution VALUES(548,' Petilil',NULL,' Sun Stone',' Egg',' Lilligant');
INSERT INTO Evolution VALUES(549,' Lilligant',NULL,NULL,'Petilil',NULL);
INSERT INTO Evolution VALUES(561,' Sigilyph',NULL,NULL,' Egg',NULL);
INSERT INTO Evolution VALUES(580,' Ducklett',35,'Normal','Egg',' Swanna');
INSERT INTO Evolution VALUES(581,' Swanna',NULL,NULL,'Swanna',NULL);
INSERT INTO Evolution VALUES(587,' Emolga',NULL,NULL,'Egg',NULL);
INSERT INTO Evolution VALUES(621,' Drudigon',NULL,NULL,' Egg',NULL);
INSERT INTO Evolution VALUES(650,' Chespin',16,' Normal','Egg','Quilladin');
INSERT INTO Evolution VALUES(651,' Quilladin',36,'Normal','Chespin','Chesnaught');
INSERT INTO Evolution VALUES(652,' Chesnaught',NULL,NULL,' Quilladin',NULL);
INSERT INTO Evolution VALUES(664,' Scatterbug',9,'Normal','Egg','Spewpa');
INSERT INTO Evolution VALUES(665,'Spewpa',12,'Normal','Scatterbug','Vivillon');
INSERT INTO Evolution VALUES(666,'Vivillon',NULL,NULL,'Spewpa',NULL);
INSERT INTO Evolution VALUES(698,' Amaura',39,'Evolve at night',' Egg',' Aurorus');
INSERT INTO Evolution VALUES(699,' Aurorus',NULL,NULL,'Amaura',NULL);