INSERT INTO Badges VALUES('Officer Jenny',' Thunder');
INSERT INTO Badges VALUES('Winona',' Feather');
INSERT INTO Badges VALUES('Whitney',' Plain');
INSERT INTO Badges VALUES('Violet',' Cascade');
INSERT INTO Badges VALUES('Valerie',' Fairy');
INSERT INTO Badges VALUES('Skyla',' Jet');
INSERT INTO Badges VALUES('Sabrina','Marsh');
INSERT INTO Badges VALUES('Lenora',' Basic');
INSERT INTO Badges VALUES('Iris',' Legend');
INSERT INTO Badges VALUES('Blaine',' Volcano');
INSERT INTO Badges VALUES('Blue',' Earth');
INSERT INTO Badges VALUES('Brawly',' Knuckle');
INSERT INTO Badges VALUES('Brock',' Boulder');
INSERT INTO Badges VALUES('Brycen',' Freeze');
INSERT INTO Badges VALUES('Bugsy',' Hive');
INSERT INTO Badges VALUES('Burgh',' Insect');
INSERT INTO Badges VALUES('Byron',' Mine');
INSERT INTO Badges VALUES('Candice',' Icicle');
INSERT INTO Badges VALUES('Cheren',' Basic');
INSERT INTO Badges VALUES('Chili',' Trio');
INSERT INTO Badges VALUES('Chuck',' Storm');
INSERT INTO Badges VALUES('Cilan',' Trio');
INSERT INTO Badges VALUES('Cissy',' Coral-Eye');
INSERT INTO Badges VALUES('Clair',' Rising');
INSERT INTO Badges VALUES('Clay',' Quake');
INSERT INTO Badges VALUES('Cress',' Trio');
INSERT INTO Badges VALUES('Daisy',' Cascade');
INSERT INTO Badges VALUES('Danny',' Sea Ruby');
INSERT INTO Badges VALUES('Drayden',' Legend');
INSERT INTO Badges VALUES('Elesa',' Bolt');
INSERT INTO Badges VALUES('Erika',' Rainbow');
INSERT INTO Badges VALUES('Falkner',' Zephyr');
INSERT INTO Badges VALUES('Fantina',' Relic');
INSERT INTO Badges VALUES('Flannery',' Heat');
INSERT INTO Badges VALUES('Flint',' Boulder');
INSERT INTO Badges VALUES('Forrest',' Boulder');
INSERT INTO Badges VALUES('Gardenia',' Forest');
INSERT INTO Badges VALUES('Giovanni',' Earth');
INSERT INTO Badges VALUES('Grant',' Cliff');
INSERT INTO Badges VALUES('Janine',' Soul');
INSERT INTO Badges VALUES('Jasmine',' Mineral');
INSERT INTO Badges VALUES('Jaun',' Rain');
INSERT INTO Badges VALUES('Koga',' Soul');
INSERT INTO Badges VALUES('Korrina',' Rumble');
INSERT INTO Badges VALUES('Lily',' Cascade');
INSERT INTO Badges VALUES('Lola',' Boulder');
INSERT INTO Badges VALUES('Luana',' Jade Star');
INSERT INTO Badges VALUES('Marlon',' Wave');
INSERT INTO Badges VALUES('Maylene',' Cobble');
INSERT INTO Badges VALUES('Misty',' Cascade');
INSERT INTO Badges VALUES('Morty',' Fog');
INSERT INTO Badges VALUES('Norman',' Balance');
INSERT INTO Badges VALUES('Olympia',' Psychic');
INSERT INTO Badges VALUES('Pryce',' Glacier');
INSERT INTO Badges VALUES('Ramos',' Plant');
INSERT INTO Badges VALUES('Roark',' Coal');
INSERT INTO Badges VALUES('Roxanne',' Stone');
INSERT INTO Badges VALUES('Roxie',' Toxic');
INSERT INTO Badges VALUES('Rudy',' Spike Shell');
INSERT INTO Badges VALUES('Lt. Surge',' Thunder');
INSERT INTO Badges VALUES('Tate & Liza',' Mind');
INSERT INTO Badges VALUES('Viola',' Bug');
INSERT INTO Badges VALUES('Volkner',' Beacon');
INSERT INTO Badges VALUES('Crasher Wake',' Fen');
INSERT INTO Badges VALUES('Wallace',' Rain');
INSERT INTO Badges VALUES('Wattson',' Dynamo');
INSERT INTO Badges VALUES('Wulfric',' Iceberg');