INSERT INTO Owns VALUES('Dr. Abby ', 'Delcatty', 	301);
INSERT INTO Owns VALUES('Abigail ', 'Raichu', 26);
INSERT INTO Owns VALUES('Greta ', 'Heracross', 214);
INSERT INTO Owns VALUES('Queen Ilene', 'Mime Jr.', 439);
INSERT INTO Owns VALUES('Officer Jenny', 'Growlithe', 58);
INSERT INTO Owns VALUES('Officer Jenny', 'Squirtle', 7);
INSERT INTO Owns VALUES('Katie', 'Venomoth', 49);
INSERT INTO Owns VALUES('Katie ', 'Golduck', 55);
INSERT INTO Owns VALUES('Katie ', 'Dugtrio', 51);
INSERT INTO Owns VALUES('Katie ', 'Scizor', 212);
INSERT INTO Owns VALUES('May ', 'Beautifly', 267);
INSERT INTO Owns VALUES('May ', 'Skitty', 300);
INSERT INTO Owns VALUES('May ', 'Venusaur', 3);
INSERT INTO Owns VALUES('May ', 'Munchlax', 446);
INSERT INTO Owns VALUES('May ', 'Wartortle', 8);
INSERT INTO Owns VALUES('Mona ', 'Lilligant', 549);
INSERT INTO Owns VALUES('Solana', 'Plusle', 311);
INSERT INTO Owns VALUES('Phoebe', 'Sableye', 302);
INSERT INTO Owns VALUES('Annie Proctor', 'Armaldo', 348);
INSERT INTO Owns VALUES('Ramona', 'Arcanine', 	59);
INSERT INTO Owns VALUES('Temacu ', 'Nidorina', 	30);
INSERT INTO Owns VALUES('Temacu ', 'Nidorino', 	33);
INSERT INTO Owns VALUES('Nini ', 'Smoochum', 	238);
INSERT INTO Owns VALUES('Nini ', 'Farfetchd', 	83);
INSERT INTO Owns VALUES('Suzy ', 'Vulpix', 	37);
INSERT INTO Owns VALUES('Ursula ', 'Plusle', 	311);
INSERT INTO Owns VALUES('Ursula ', 'Jigglypuff', 	39);
INSERT INTO Owns VALUES('Ursula ', 'Vaporeon', 	134);
INSERT INTO Owns VALUES('Zoey ', 'Glameow', 	431);
INSERT INTO Owns VALUES('Zinnia ', 'Altaria', 	334);
INSERT INTO Owns VALUES('Yoko ', 'Nuzleaf', 274);
INSERT INTO Owns VALUES('Violet ', 'Vivillon', 	666);
INSERT INTO Owns VALUES('Yuuko ', 'Sunkern', 	191);
INSERT INTO Owns VALUES('Yuki ', 'Machop', 	66);
INSERT INTO Owns VALUES('Yuki ', 'Scyther', 	123);
INSERT INTO Owns VALUES('Yuki ', 'Magmar', 	126);
INSERT INTO Owns VALUES('Yellow ', 'Raticate', 	20);
INSERT INTO Owns VALUES('Yellow ', 'Doduo', 	84);
INSERT INTO Owns VALUES('Yellow', 'Graveler', 	75);
INSERT INTO Owns VALUES('Yellow ', 'Omastar', 	139);
INSERT INTO Owns VALUES('Yellow ', 'Butterfree', 	12);
INSERT INTO Owns VALUES('Yellow ', 'Pikachu', 	25);
INSERT INTO Owns VALUES('Yancy ', 'Spinda', 	327);
INSERT INTO Owns VALUES('Yai Suba', ' Wingull', 	278);
INSERT INTO Owns VALUES('Yvonne Gabena', ' Rhyhorn', 	111);
INSERT INTO Owns VALUES('Winona', '	Pelipper', 	279);
INSERT INTO Owns VALUES('Winona', '	Skarmory', 	227);
INSERT INTO Owns VALUES('Winona', '	Altaria', 	334);
INSERT INTO Owns VALUES('Whitney', '	Clefairy', 	35);
INSERT INTO Owns VALUES('Violet', '	Dewgong', 	87);
INSERT INTO Owns VALUES('Violet', '	Seaking', 	119);
INSERT INTO Owns VALUES('Violet', '	Goldeen', 	118);
INSERT INTO Owns VALUES('Venus', '	Delcatty', 	301);
INSERT INTO Owns VALUES('Venus', '	Steelix', 	208);
INSERT INTO Owns VALUES('Venus', '	Vileplume', 	45);
INSERT INTO Owns VALUES('Valerie', '	Mr. Mime', 122);
INSERT INTO Owns VALUES('Ultima', ' Dragonite', 	149);
INSERT INTO Owns VALUES('Tyra', '	Cloyster', 	91);
INSERT INTO Owns VALUES('Trixie', '	Golduck', 	55);
INSERT INTO Owns VALUES('Trixie', '	Pidgey', 	16);
INSERT INTO Owns VALUES('Trixie', '	Machoke', 	67);
INSERT INTO Owns VALUES('Trinity', '	Gyarados', 	130);
INSERT INTO Owns VALUES('Trinity', '	Golduck', 	55);
INSERT INTO Owns VALUES('Thief', '	Houndoom', 	229);
INSERT INTO Owns VALUES('Thief', '	Houndour', 	228);
INSERT INTO Owns VALUES('Taylor', '	Skarmory', 	227);
INSERT INTO Owns VALUES('Kidd Summers', '	Weavile', 	461);
INSERT INTO Owns VALUES('Summer', '	Pichu', 	172);
INSERT INTO Owns VALUES('Stephanie', '	Mudkip', 	258);
INSERT INTO Owns VALUES('Stella', '	Mr. Mime', 	122);
INSERT INTO Owns VALUES('Stella', '	Ponyta', 	77);
INSERT INTO Owns VALUES('Stella', '	Rapidash', 	78);
INSERT INTO Owns VALUES('Stella', '	Machoke', 	67);
INSERT INTO Owns VALUES('Stella', '	Tangela', 	114);
INSERT INTO Owns VALUES('Stella', '	Exeggcute', 	102);
INSERT INTO Owns VALUES('Stella', ' Dodrio', 	85);
INSERT INTO Owns VALUES('Millis Steel', '	Chesnaught', 	652);
INSERT INTO Owns VALUES('Spring', '	Miltank', 	241);
INSERT INTO Owns VALUES('Summer', '	Miltank', 	241);
INSERT INTO Owns VALUES('Skyla', '	Swanna', 	581);
INSERT INTO Owns VALUES('Sabrina', '	Kadabra', 	64);
INSERT INTO Owns VALUES('Sabrina', '	Mr. Mime', 	122);
INSERT INTO Owns VALUES('Sabrina', '	Venomoth', 	49);
INSERT INTO Owns VALUES('Sabrina', '	Alakazam', 	65);
INSERT INTO Owns VALUES('Nancy', '	Persian', 	53);
INSERT INTO Owns VALUES('Nancy', 'Starmie', 	121);
INSERT INTO Owns VALUES('Lilaa', '	Delcatty', 	301);
INSERT INTO Owns VALUES('Haley', '	Feebas', 	349);
INSERT INTO Owns VALUES('Lenora', '	Watchog', 	505);
INSERT INTO Owns VALUES('Ginger', '	Girafarig', 	203);
INSERT INTO Owns VALUES('Autumn', '	Miltank', 	241);
INSERT INTO Owns VALUES('Arielle', ' Ledyba', 	165);
INSERT INTO Owns VALUES('Bianca', '	Oshawott', 	501);
INSERT INTO Owns VALUES('Billy Jo', '	Koffing', 	109);
INSERT INTO Owns VALUES('Allegra', '	Infernape', 	392);
INSERT INTO Owns VALUES('Cassidy', '	Raticate', 	20);
INSERT INTO Owns VALUES('Cassidy', '	Houndour', 	228);
INSERT INTO Owns VALUES('Cassidy', '	Sableye', 	302);
INSERT INTO Owns VALUES('Cassidy', '	Tentacruel', 	73);
INSERT INTO Owns VALUES('Jessie', '	Wobbuffet', 	202);
INSERT INTO Owns VALUES('Juliet', '	Illumise', 	314);
INSERT INTO Owns VALUES('Iris', '	Druddigon', 	621);
INSERT INTO Owns VALUES('Giselle', '	Graveler', 	75);
INSERT INTO Owns VALUES('Giselle', '	Cubone', 	104);
INSERT INTO Owns VALUES('Mars', '	Zubat', 	41);
INSERT INTO Owns VALUES('Mars', '	Purugly', 	432);
INSERT INTO Owns VALUES('Jessebelle', '	Vileplume', 	45);
INSERT INTO Owns VALUES('Maisy', '	Slowpoke', 	79);
INSERT INTO Owns VALUES('Luna', '	Scizor', 	212);
INSERT INTO Owns VALUES('Janet', '	Beautifly', 	267);
INSERT INTO Owns VALUES('Cassandra', '	Persian', 	53);
INSERT INTO Owns VALUES('Cassandra', '	Parasect', 	47);
INSERT INTO Owns VALUES('Aldith', '	Weavile', 	461);
INSERT INTO Owns VALUES('Celosia', '	Pikachu', 	25);
INSERT INTO Owns VALUES('Bailey', '	Vileplume', 	45);
INSERT INTO Owns VALUES('Ellie', '	Pikachu', 	25);
INSERT INTO Owns VALUES('Flora', '	Weavile', 	461);
INSERT INTO Owns VALUES('Gemma', '	Lapras', 	131);
INSERT INTO Owns VALUES('Gail', '	Druddigon', 	621);
INSERT INTO Owns VALUES('Caitlin', '	Sigilyph', 	561);
INSERT INTO Owns VALUES('Bebe', '	Eevee', 	133);
INSERT INTO Owns VALUES('Aaron', '	Beautifly', 	267);
INSERT INTO Owns VALUES('Aaron', '	Heracross', 	214);
INSERT INTO Owns VALUES('Agatha', '	Gengar', 	94);
INSERT INTO Owns VALUES('Agatha', '	Golbat', 	42);
INSERT INTO Owns VALUES('Agatha', '	Haunter', 	93);
INSERT INTO Owns VALUES('Agatha', '	Arbok', 	24);
INSERT INTO Owns VALUES('Blaine', '	Growlithe', 	58);
INSERT INTO Owns VALUES('Blaine', '	Ponyta', 	77);
INSERT INTO Owns VALUES('Blaine', '	Rapidash', 	78);
INSERT INTO Owns VALUES('Blaine', '	Arcanine', 	59);
INSERT INTO Owns VALUES('Blue', '	Sandslash', 	28);
INSERT INTO Owns VALUES('Blue', '	Alakazam', 	65);
INSERT INTO Owns VALUES('Blue', '	Exeggutor', 	103);
INSERT INTO Owns VALUES('Blue', '	Ninetales', 	38);
INSERT INTO Owns VALUES('Blue', '	Magneton', 	82);
INSERT INTO Owns VALUES('Blue', '	Vaporeon', 	134);
INSERT INTO Owns VALUES('Brawly', '	Machop', 	66);
INSERT INTO Owns VALUES('Brock', '	Geodude', 	74);
INSERT INTO Owns VALUES('Brock', '	Onix', 	95);
INSERT INTO Owns VALUES('Brycen', '	Cryogonal', 	615);
INSERT INTO Owns VALUES('Bugsy', '	Metapod', 	11);
INSERT INTO Owns VALUES('Bugsy', '	Kakuna', 	14);
INSERT INTO Owns VALUES('Bugsy', '	Scyther', 	123);
INSERT INTO Owns VALUES('Burgh', '	Vivillon', 	666);
INSERT INTO Owns VALUES('Byron', '	Steelix', 	208);
INSERT INTO Owns VALUES('Byron', '	Bastiodon', 	411);
INSERT INTO Owns VALUES('Candice', '	Sneasel', 	215);
INSERT INTO Owns VALUES('Cheren', '	Tepig', 	498);
INSERT INTO Owns VALUES('Chili', '	Eevee', 	133);
INSERT INTO Owns VALUES('Chuck', '	Primeape', 	57);
INSERT INTO Owns VALUES('Chuck', '	Poliwrath', 	62);
INSERT INTO Owns VALUES('Cilan', '	Eevee', 	133);
INSERT INTO Owns VALUES('Cissy', '	Seadra', 	117);
INSERT INTO Owns VALUES('Cissy', '	Blastoise', 	9);
INSERT INTO Owns VALUES('Clair', '	Dragonair', 	148);
INSERT INTO Owns VALUES('Clair', '	Kingdra', 	230);
INSERT INTO Owns VALUES('Clay', '	Sandslash', 	28);
INSERT INTO Owns VALUES('Cress', '	Eevee', 	133);
INSERT INTO Owns VALUES('Daisy', '	Poliwhirl', 	61);
INSERT INTO Owns VALUES('Danny', '	Nidoqueen', 	31);
INSERT INTO Owns VALUES('Danny', '	Machoke', 	67);
INSERT INTO Owns VALUES('Danny', '	Scyther', 	123);
INSERT INTO Owns VALUES('Danny', '	Electrode', 	101);
INSERT INTO Owns VALUES('Danny', '	Geodude', 	74);
INSERT INTO Owns VALUES('Drayden', '	Druddigon', 	621);
INSERT INTO Owns VALUES('Elesa', '	Emolga', 	587);
INSERT INTO Owns VALUES('Erika', '	Victreebel', 	71);
INSERT INTO Owns VALUES('Erika', '	Tangela', 	114);
INSERT INTO Owns VALUES('Erika', '	Vileplume', 	45);
INSERT INTO Owns VALUES('Falkner', '	Pidgey', 	16);
INSERT INTO Owns VALUES('Falkner', '	Pidgeotto', 	17);
INSERT INTO Owns VALUES('Fantina', '	Gengar', 	94);
INSERT INTO Owns VALUES('Flannery', '	Torkoal', 	324);
INSERT INTO Owns VALUES('Flint', '	Golem', 	76);
INSERT INTO Owns VALUES('Flint', '	Rhydon', 	112);
INSERT INTO Owns VALUES('Flint', '	Onix', 	95);
INSERT INTO Owns VALUES('Forrest', '	Rhyperior', 	464);
INSERT INTO Owns VALUES('Gardenia', '	Turtwig', 	387);
INSERT INTO Owns VALUES('Giovanni', '	Onix', 	95);
INSERT INTO Owns VALUES('Giovanni', '	Rhyhorn', 	111);
INSERT INTO Owns VALUES('Giovanni', '	Kangaskhan', 	115);
INSERT INTO Owns VALUES('Grant', '	Amaura', 	698);
INSERT INTO Owns VALUES('James', '	Victreebel', 	71);
INSERT INTO Owns VALUES('Janine', '	Crobat', 	169);
INSERT INTO Owns VALUES('Janine', '	Weezing', 	110);
INSERT INTO Owns VALUES('Janine', '	Venomoth', 	49);
INSERT INTO Owns VALUES('Jasmine', '	Magnetmite', 	81);
INSERT INTO Owns VALUES('Jasmine', '	Steelix', 	208);
INSERT INTO Owns VALUES('Jaun', '	Kingdra', 	230);
INSERT INTO Owns VALUES('Kaz', '	Electabuzz', 	125);
INSERT INTO Owns VALUES('Kiyo', '	Hitmonchan', 	107);
INSERT INTO Owns VALUES('Kiyo', '	Hitmonlee', 	106);
INSERT INTO Owns VALUES('Koga', '	Koffing', 	109);
INSERT INTO Owns VALUES('Koga', '	Muk', 	89);
INSERT INTO Owns VALUES('Koga', '	Weezing', 	110);
INSERT INTO Owns VALUES('Korrina', '	Lucario', 	448);
INSERT INTO Owns VALUES('Lily', '	Goldeen', 	118);
INSERT INTO Owns VALUES('Lola', '	Blastoise', 	9);
INSERT INTO Owns VALUES('Lola', '	Gyarados', 	130);
INSERT INTO Owns VALUES('Lola', 'Vaporeon', 	134);
INSERT INTO Owns VALUES('Lola', '	Poliwag', 	60);
INSERT INTO Owns VALUES('Lola', '	Slowpoke', 	79);
INSERT INTO Owns VALUES('Lola', '	Tentacruel', 	73);
INSERT INTO Owns VALUES('Luana', '	Alakazam', 	65);
INSERT INTO Owns VALUES('Luana', '	Marowak', 	105);
INSERT INTO Owns VALUES('Marlon', '	Wailord', 	321);
INSERT INTO Owns VALUES('Maylene', '	Machoke', 	67);
INSERT INTO Owns VALUES('Maylene', '	Lucario', 	448);
INSERT INTO Owns VALUES('Misty', '	Staryu', 120);
INSERT INTO Owns VALUES('Misty', '	Starmie', 	121);
INSERT INTO Owns VALUES('Mr. Moore', '	Wingull', 	278);
INSERT INTO Owns VALUES('Morty', '	Gastly', 	92);
INSERT INTO Owns VALUES('Morty', '	Haunter', 	93);
INSERT INTO Owns VALUES('Morty	', 'Gengar', 	94);
INSERT INTO Owns VALUES('Norman', '	Vigoroth', 	288);
INSERT INTO Owns VALUES('Olympia', '	Sigilyph', 	561);
INSERT INTO Owns VALUES('Pryce', '	Seel', 	86);
INSERT INTO Owns VALUES('Pryce', '	Dewgong', 	87);
INSERT INTO Owns VALUES('Ramos', 'Weepinbell', 	70);
INSERT INTO Owns VALUES('Roark', '	Geodude', 	74);
INSERT INTO Owns VALUES('Roark', '	Onix', 	95);
INSERT INTO Owns VALUES('Roxanne', '	Geodude', 	74);
INSERT INTO Owns VALUES('Roxie', 'Koffing', 	109);
INSERT INTO Owns VALUES('Rudy', 'Electabuzz', 	125);
INSERT INTO Owns VALUES('Rudy', 'Exeggutor', 	103);
INSERT INTO Owns VALUES('Rudy', 'Starmie', 	121);
INSERT INTO Owns VALUES('Lt. Surge', 'Voltorb', 100);
INSERT INTO Owns VALUES('Lt. Surge', 'Pikachu', 25);
INSERT INTO Owns VALUES('Lt. Surge', 'Raichu', 26);
INSERT INTO Owns VALUES('Tate & Liza', 'Lunatone', 337);
INSERT INTO Owns VALUES('Viola', 'Vivillon', 66);
INSERT INTO Owns VALUES('Volkner', 'Raichu', 26);
INSERT INTO Owns VALUES('Crasher Wake', '	Gyarados', 130);
INSERT INTO Owns VALUES('Wallace', 'Seaking', 119);
INSERT INTO Owns VALUES('Wallace', 'Milotic', 350);
INSERT INTO Owns VALUES('Wattson', 'Voltorb', 100);
INSERT INTO Owns VALUES('Wattson', 'Magnemite', 81);
INSERT INTO Owns VALUES('Wattson', 'Magneton', 82);
INSERT INTO Owns VALUES('Wulfric', 'Cryogonal', 615);
INSERT INTO Owns VALUES('Yas', 'Scyther', 123);
INSERT INTO Owns VALUES('', '', );