INSERT INTO Appears_In VALUES(75,'Pewter');
INSERT INTO Appears_In VALUES(9,'Cerulean');
INSERT INTO Appears_In VALUES(3,'Vermilion');
INSERT INTO Appears_In VALUES(45,'Celadon');
INSERT INTO Appears_In VALUES(42,'Fuchisia');
INSERT INTO Appears_In VALUES(65,'Saffron');
INSERT INTO Appears_In VALUES(126,'Cinnabar');
INSERT INTO Appears_In VALUES(112,'Viridian');
INSERT INTO Appears_In VALUES(18,'Violet');
INSERT INTO Appears_In VALUES(165,'Azalea');
INSERT INTO Appears_In VALUES(203,'Goldenrod');
INSERT INTO Appears_In VALUES(94,'Ecruteak');
INSERT INTO Appears_In VALUES(236,'Cianwood');
INSERT INTO Appears_In VALUES(208,'Olivine');
INSERT INTO Appears_In VALUES(131,'Mahogany');
INSERT INTO Appears_In VALUES(149,'Blckthorn');
INSERT INTO Appears_In VALUES(348,'Rustboro');
INSERT INTO Appears_In VALUES(68,'Dewford');
INSERT INTO Appears_In VALUES(311,'Mauville');
INSERT INTO Appears_In VALUES(301,'Petalburg');
INSERT INTO Appears_In VALUES(279,'Fortree');
INSERT INTO Appears_In VALUES(337,'Mossdeep');
INSERT INTO Appears_In VALUES(76,'Oreburgh');
INSERT INTO Appears_In VALUES(275,'Eterna');
INSERT INTO Appears_In VALUES(448,'Veilstone');
INSERT INTO Appears_In VALUES(279,'Pastoria');
INSERT INTO Appears_In VALUES(389,'Driftveil');
INSERT INTO Appears_In VALUES(227,'Mistralton');
INSERT INTO Appears_In VALUES(461,'Icirrus');
INSERT INTO Appears_In VALUES(334,'Opelucid');
INSERT INTO Appears_In VALUES(505,'Aspertia');
INSERT INTO Appears_In VALUES(89,'Virbank');
INSERT INTO Appears_In VALUES(350,'Humilau');
INSERT INTO Appears_In VALUES(666,'Santalune');
INSERT INTO Appears_In VALUES(95,'Cyllage');
INSERT INTO Appears_In VALUES(106,'Shalour');
INSERT INTO Appears_In VALUES(652,'Coumarine');
INSERT INTO Appears_In VALUES(40,'Laverre');
INSERT INTO Appears_In VALUES(561,'Anistar');
INSERT INTO Appears_In VALUES(699,'Snowbelle');
INSERT INTO Appears_In VALUES(581,'Mikan');
INSERT INTO Appears_In VALUES(464,'Navel');
INSERT INTO Appears_In VALUES(389,'Trovita');
INSERT INTO Appears_In VALUES(439,'Kumquat');
INSERT INTO Appears_In VALUES(467,'Lavaridge');


# insert data into Attack table
INSERT INTO Attack VALUES ('Name', Power, 'Type');
INSERT INTO Attack VALUES ('Pound', 40, 'Normal');
INSERT INTO Attack VALUES ('Karate Chop', 50, 'Fighting');
INSERT INTO Attack VALUES ('Double Slap', 15, 'Normal');
INSERT INTO Attack VALUES ('Comet Punch', 18, 'Normal');
INSERT INTO Attack VALUES ('Mega Punch', 80, 'Normal');
INSERT INTO Attack VALUES ('Pay Day', 40, 'Normal');
INSERT INTO Attack VALUES ('Fire Punch', 75, 'Fire');
INSERT INTO Attack VALUES ('Ice Punch', 75, 'Ice');
INSERT INTO Attack VALUES ('Thunder Punch', 75, 'Electric');
INSERT INTO Attack VALUES ('Scratch', 40, 'Normal');
INSERT INTO Attack VALUES ('Vice Grip', 55, 'Normal');
INSERT INTO Attack VALUES ('Guillotine', , 'Normal');
INSERT INTO Attack VALUES ('Razor Wind', 80, 'Normal');
INSERT INTO Attack VALUES ('Swords Dance', , 'Normal');
INSERT INTO Attack VALUES ('Cut', 50, 'Normal');
INSERT INTO Attack VALUES ('Gust', 40, 'Flying');
INSERT INTO Attack VALUES ('Wing Attack', 60, 'Flying');
INSERT INTO Attack VALUES ('Whirlwind', , 'Normal');
INSERT INTO Attack VALUES ('Fly', 90, 'Flying');
INSERT INTO Attack VALUES ('Bind', 15, 'Normal');
INSERT INTO Attack VALUES ('Slam', 80, 'Normal');
INSERT INTO Attack VALUES ('Vine Whip', 45, 'Grass');
INSERT INTO Attack VALUES ('Stomp', 65, 'Normal');
INSERT INTO Attack VALUES ('Double Kick', 30, 'Fighting');
INSERT INTO Attack VALUES ('Mega Kick', 120, 'Normal');
INSERT INTO Attack VALUES ('Jump Kick', 100, 'Fighting');
INSERT INTO Attack VALUES ('Rolling Kick', 60, 'Fighting');
INSERT INTO Attack VALUES ('Sand Attack', , 'Ground');
INSERT INTO Attack VALUES ('Headbutt', 70, 'Normal');
INSERT INTO Attack VALUES ('Horn Attack', 65, 'Normal');
INSERT INTO Attack VALUES ('Fury Attack', 15, 'Normal');
INSERT INTO Attack VALUES ('Horn Drill', , 'Normal');
INSERT INTO Attack VALUES ('Tackle', 50, 'Normal');
INSERT INTO Attack VALUES ('Body Slam', 85, 'Normal');
INSERT INTO Attack VALUES ('Wrap', 15, 'Normal');
INSERT INTO Attack VALUES ('Take Down', 90, 'Normal');
INSERT INTO Attack VALUES ('Thrash', 120, 'Normal');
INSERT INTO Attack VALUES ('Double-Edge', 120, 'Normal');
INSERT INTO Attack VALUES ('Tail Whip', , 'Normal');
INSERT INTO Attack VALUES ('Poison Sting', 15, 'Poison');
INSERT INTO Attack VALUES ('Twineedle', 25, 'Bug');
INSERT INTO Attack VALUES ('Pin Missile', 25, 'Bug');
INSERT INTO Attack VALUES ('Leer', , 'Normal');
INSERT INTO Attack VALUES ('Bite', 60, 'Dark');
INSERT INTO Attack VALUES ('Growl', , 'Normal');
INSERT INTO Attack VALUES ('Roar', , 'Normal');
INSERT INTO Attack VALUES ('Sing', , 'Normal');
INSERT INTO Attack VALUES ('Supersonic', , 'Normal');
INSERT INTO Attack VALUES ('Sonic Boom', , 'Normal');
INSERT INTO Attack VALUES ('Disable', , 'Normal');
INSERT INTO Attack VALUES ('Acid', 40, 'Poison');
INSERT INTO Attack VALUES ('Ember', 40, 'Fire');
INSERT INTO Attack VALUES ('Flamethrower', 90, 'Fire');
INSERT INTO Attack VALUES ('Mist', , 'Ice');
INSERT INTO Attack VALUES ('Water Gun', 40, 'Water');
INSERT INTO Attack VALUES ('Hydro Pump', 110, 'Water');
INSERT INTO Attack VALUES ('Surf', 90, 'Water');
INSERT INTO Attack VALUES ('Ice Beam', 90, 'Ice');
INSERT INTO Attack VALUES ('Blizzard', 110, 'Ice');
INSERT INTO Attack VALUES ('Psybeam', 65, 'Psychic');
INSERT INTO Attack VALUES ('Bubble Beam', 65, 'Water');
INSERT INTO Attack VALUES ('Aurora Beam', 65, 'Ice');
INSERT INTO Attack VALUES ('Hyper Beam', 150, 'Normal');
INSERT INTO Attack VALUES ('Peck', 35, 'Flying');
INSERT INTO Attack VALUES ('Drill Peck', 80, 'Flying');
INSERT INTO Attack VALUES ('Submission', 80, 'Fighting');
INSERT INTO Attack VALUES ('Low Kick', , 'Fighting');
INSERT INTO Attack VALUES ('Counter', , 'Fighting');
INSERT INTO Attack VALUES ('Seismic Toss', , 'Fighting');
INSERT INTO Attack VALUES ('Strength', 80, 'Normal');
INSERT INTO Attack VALUES ('Absorb', 20, 'Grass');
INSERT INTO Attack VALUES ('Mega Drain', 40, 'Grass');
INSERT INTO Attack VALUES ('Leech Seed', , 'Grass');
INSERT INTO Attack VALUES ('Growth', , 'Normal');
INSERT INTO Attack VALUES ('Razor Leaf', 55, 'Grass');
INSERT INTO Attack VALUES ('Solar Beam', 120, 'Grass');
INSERT INTO Attack VALUES ('Poison Powder', , 'Poison');
INSERT INTO Attack VALUES ('Stun Spore', , 'Grass');
INSERT INTO Attack VALUES ('Sleep Powder', , 'Grass');
INSERT INTO Attack VALUES ('Petal Dance', 120, 'Grass');
INSERT INTO Attack VALUES ('String Shot', , 'Bug');
INSERT INTO Attack VALUES ('Dragon Rage', , 'Dragon');
INSERT INTO Attack VALUES ('Fire Spin', 35, 'Fire');
INSERT INTO Attack VALUES ('Thunder Shock', 40, 'Electric');
INSERT INTO Attack VALUES ('Thunderbolt', 90, 'Electric');
INSERT INTO Attack VALUES ('Thunder Wave', , 'Electric');
INSERT INTO Attack VALUES ('Thunder', 110, 'Electric');
INSERT INTO Attack VALUES ('Rock Throw', 50, 'Rock');
INSERT INTO Attack VALUES ('Earthquake', 100, 'Ground');
INSERT INTO Attack VALUES ('Fissure', , 'Ground');
INSERT INTO Attack VALUES ('Dig', 80, 'Ground');
INSERT INTO Attack VALUES ('Toxic', , 'Poison');
INSERT INTO Attack VALUES ('Confusion', 50, 'Psychic');
INSERT INTO Attack VALUES ('Psychic', 90, 'Psychic');
INSERT INTO Attack VALUES ('Hypnosis', , 'Psychic');
INSERT INTO Attack VALUES ('Meditate', , 'Psychic');
INSERT INTO Attack VALUES ('Agility', , 'Psychic');
INSERT INTO Attack VALUES ('Quick Attack', 40, 'Normal');
INSERT INTO Attack VALUES ('Rage', 20, 'Normal');
INSERT INTO Attack VALUES ('Teleport', , 'Psychic');
INSERT INTO Attack VALUES ('Night Shade', , 'Ghost');
INSERT INTO Attack VALUES ('Mimic', , 'Normal');
INSERT INTO Attack VALUES ('Screech', , 'Normal');
INSERT INTO Attack VALUES ('Double Team', , 'Normal');
INSERT INTO Attack VALUES ('Recover', , 'Normal');
INSERT INTO Attack VALUES ('Harden', , 'Normal');
INSERT INTO Attack VALUES ('Minimize', , 'Normal');
INSERT INTO Attack VALUES ('Smokescreen', , 'Normal');
INSERT INTO Attack VALUES ('Confuse Ray', , 'Ghost');
INSERT INTO Attack VALUES ('Withdraw', , 'Water');
INSERT INTO Attack VALUES ('Defense Curl', , 'Normal');
INSERT INTO Attack VALUES ('Barrier', , 'Psychic');
INSERT INTO Attack VALUES ('Light Screen', , 'Psychic');
INSERT INTO Attack VALUES ('Haze', , 'Ice');
INSERT INTO Attack VALUES ('Reflect', , 'Psychic');
INSERT INTO Attack VALUES ('Focus Energy', , 'Normal');
INSERT INTO Attack VALUES ('Bide', , 'Normal');
INSERT INTO Attack VALUES ('Metronome', , 'Normal');
INSERT INTO Attack VALUES ('Mirror Move', , 'Flying');
INSERT INTO Attack VALUES ('Self-Destruct', 200, 'Normal');
INSERT INTO Attack VALUES ('Egg Bomb', 100, 'Normal');
INSERT INTO Attack VALUES ('Lick', 30, 'Ghost');
INSERT INTO Attack VALUES ('Smog', 30, 'Poison');
INSERT INTO Attack VALUES ('Sludge', 65, 'Poison');
INSERT INTO Attack VALUES ('Bone Club', 65, 'Ground');
INSERT INTO Attack VALUES ('Fire Blast', 110, 'Fire');
INSERT INTO Attack VALUES ('Waterfall', 80, 'Water');
INSERT INTO Attack VALUES ('Clamp', 35, 'Water');
INSERT INTO Attack VALUES ('Swift', 60, 'Normal');
INSERT INTO Attack VALUES ('Skull Bash', 130, 'Normal');
INSERT INTO Attack VALUES ('Spike Cannon', 20, 'Normal');
INSERT INTO Attack VALUES ('Constrict', 10, 'Normal');
INSERT INTO Attack VALUES ('Amnesia', , 'Psychic');
INSERT INTO Attack VALUES ('Kinesis', , 'Psychic');
INSERT INTO Attack VALUES ('Soft-Boiled', , 'Normal');
INSERT INTO Attack VALUES ('High Jump Kick', 130, 'Fighting');
INSERT INTO Attack VALUES ('Glare', , 'Normal');
INSERT INTO Attack VALUES ('Dream Eater', 100, 'Psychic');
INSERT INTO Attack VALUES ('Poison Gas', , 'Poison');
INSERT INTO Attack VALUES ('Barrage', 15, 'Normal');
INSERT INTO Attack VALUES ('Leech Life', 20, 'Bug');
INSERT INTO Attack VALUES ('Lovely Kiss', , 'Normal');
INSERT INTO Attack VALUES ('Sky Attack', 140, 'Flying');
INSERT INTO Attack VALUES ('Transform', , 'Normal');
INSERT INTO Attack VALUES ('Bubble', 40, 'Water');
INSERT INTO Attack VALUES ('Dizzy Punch', 70, 'Normal');
INSERT INTO Attack VALUES ('Spore', , 'Grass');
INSERT INTO Attack VALUES ('Flash', , 'Normal');
INSERT INTO Attack VALUES ('Psywave', , 'Psychic');
INSERT INTO Attack VALUES ('Splash', , 'Normal');
INSERT INTO Attack VALUES ('Acid Armor', , 'Poison');
INSERT INTO Attack VALUES ('Crabhammer', 100, 'Water');
INSERT INTO Attack VALUES ('Explosion', 250, 'Normal');
INSERT INTO Attack VALUES ('Fury Swipes', 18, 'Normal');
INSERT INTO Attack VALUES ('Bonemerang', 50, 'Ground');
INSERT INTO Attack VALUES ('Rest', , 'Psychic');
INSERT INTO Attack VALUES ('Rock Slide', 75, 'Rock');
INSERT INTO Attack VALUES ('Hyper Fang', 80, 'Normal');
INSERT INTO Attack VALUES ('Sharpen', , 'Normal');
INSERT INTO Attack VALUES ('Conversion', , 'Normal');
INSERT INTO Attack VALUES ('Tri Attack', 80, 'Normal');
INSERT INTO Attack VALUES ('Super Fang', , 'Normal');
INSERT INTO Attack VALUES ('Slash', 70, 'Normal');
INSERT INTO Attack VALUES ('Substitute', , 'Normal');
INSERT INTO Attack VALUES ('Struggle', 50, 'Normal');
INSERT INTO Attack VALUES ('Sketch', , 'Normal');
INSERT INTO Attack VALUES ('Triple Kick', 10, 'Fighting');
INSERT INTO Attack VALUES ('Thief', 60, 'Dark');
INSERT INTO Attack VALUES ('Spider Web', , 'Bug');
INSERT INTO Attack VALUES ('Mind Reader', , 'Normal');
INSERT INTO Attack VALUES ('Nightmare', , 'Ghost');
INSERT INTO Attack VALUES ('Flame Wheel', 60, 'Fire');
INSERT INTO Attack VALUES ('Snore', 50, 'Normal');
INSERT INTO Attack VALUES ('Curse', , 'Ghost');
INSERT INTO Attack VALUES ('Flail', , 'Normal');
INSERT INTO Attack VALUES ('Conversion 2', , 'Normal');
INSERT INTO Attack VALUES ('Aeroblast', 100, 'Flying');
INSERT INTO Attack VALUES ('Cotton Spore', , 'Grass');
INSERT INTO Attack VALUES ('Reversal', , 'Fighting');
INSERT INTO Attack VALUES ('Spite', , 'Ghost');
INSERT INTO Attack VALUES ('Powder Snow', 40, 'Ice');
INSERT INTO Attack VALUES ('Protect', , 'Normal');
INSERT INTO Attack VALUES ('Mach Punch', 40, 'Fighting');
INSERT INTO Attack VALUES ('Scary Face', , 'Normal');
INSERT INTO Attack VALUES ('Feint Attack', 60, 'Dark');
INSERT INTO Attack VALUES ('Sweet Kiss', , 'Fairy');
INSERT INTO Attack VALUES ('Belly Drum', , 'Normal');
INSERT INTO Attack VALUES ('Sludge Bomb', 90, 'Poison');
INSERT INTO Attack VALUES ('Mud-Slap', 20, 'Ground');
INSERT INTO Attack VALUES ('Octazooka', 65, 'Water');
INSERT INTO Attack VALUES ('Spikes', , 'Ground');
INSERT INTO Attack VALUES ('Zap Cannon', 120, 'Electric');
INSERT INTO Attack VALUES ('Foresight', , 'Normal');
INSERT INTO Attack VALUES ('Destiny Bond', , 'Ghost');
INSERT INTO Attack VALUES ('Perish Song', , 'Normal');
INSERT INTO Attack VALUES ('Icy Wind', 55, 'Ice');
INSERT INTO Attack VALUES ('Detect', , 'Fighting');
INSERT INTO Attack VALUES ('Bone Rush', 25, 'Ground');
INSERT INTO Attack VALUES ('Lock-On', , 'Normal');
INSERT INTO Attack VALUES ('Outrage', 120, 'Dragon');
INSERT INTO Attack VALUES ('Sandstorm', , 'Rock');
INSERT INTO Attack VALUES ('Giga Drain', 75, 'Grass');
INSERT INTO Attack VALUES ('Endure', , 'Normal');
INSERT INTO Attack VALUES ('Charm', , 'Fairy');
INSERT INTO Attack VALUES ('Rollout', 30, 'Rock');
INSERT INTO Attack VALUES ('False Swipe', 40, 'Normal');
INSERT INTO Attack VALUES ('Swagger', , 'Normal');
INSERT INTO Attack VALUES ('Milk Drink', , 'Normal');
INSERT INTO Attack VALUES ('Spark', 65, 'Electric');
INSERT INTO Attack VALUES ('Fury Cutter', 40, 'Bug');
INSERT INTO Attack VALUES ('Steel Wing', 70, 'Steel');
INSERT INTO Attack VALUES ('Mean Look', , 'Normal');
INSERT INTO Attack VALUES ('Attract', , 'Normal');
INSERT INTO Attack VALUES ('Sleep Talk', , 'Normal');
INSERT INTO Attack VALUES ('Heal Bell', , 'Normal');
INSERT INTO Attack VALUES ('Return', , 'Normal');
INSERT INTO Attack VALUES ('Present', , 'Normal');
INSERT INTO Attack VALUES ('Frustration', , 'Normal');
INSERT INTO Attack VALUES ('Safeguard', , 'Normal');
INSERT INTO Attack VALUES ('Pain Split', , 'Normal');
INSERT INTO Attack VALUES ('Sacred Fire', 100, 'Fire');
INSERT INTO Attack VALUES ('Magnitude', , 'Ground');
INSERT INTO Attack VALUES ('Dynamic Punch', 100, 'Fighting');
INSERT INTO Attack VALUES ('Megahorn', 120, 'Bug');
INSERT INTO Attack VALUES ('Dragon Breath', 60, 'Dragon');
INSERT INTO Attack VALUES ('Baton Pass', , 'Normal');
INSERT INTO Attack VALUES ('Encore', , 'Normal');
INSERT INTO Attack VALUES ('Pursuit', 40, 'Dark');
INSERT INTO Attack VALUES ('Rapid Spin', 20, 'Normal');
INSERT INTO Attack VALUES ('Sweet Scent', , 'Normal');
INSERT INTO Attack VALUES ('Iron Tail', 100, 'Steel');
INSERT INTO Attack VALUES ('Metal Claw', 50, 'Steel');
INSERT INTO Attack VALUES ('Vital Throw', 70, 'Fighting');
INSERT INTO Attack VALUES ('Morning Sun', , 'Normal');
INSERT INTO Attack VALUES ('Synthesis', , 'Grass');
INSERT INTO Attack VALUES ('Moonlight', , 'Fairy');
INSERT INTO Attack VALUES ('Hidden Power', 60, 'Normal');
INSERT INTO Attack VALUES ('Cross Chop', 100, 'Fighting');
INSERT INTO Attack VALUES ('Twister', 40, 'Dragon');
INSERT INTO Attack VALUES ('Rain Dance', , 'Water');
INSERT INTO Attack VALUES ('Sunny Day', , 'Fire');
INSERT INTO Attack VALUES ('Crunch', 80, 'Dark');
INSERT INTO Attack VALUES ('Mirror Coat', , 'Psychic');
INSERT INTO Attack VALUES ('Psych Up', , 'Normal');
INSERT INTO Attack VALUES ('Extreme Speed', 80, 'Normal');
INSERT INTO Attack VALUES ('Ancient Power', 60, 'Rock');
INSERT INTO Attack VALUES ('Shadow Ball', 80, 'Ghost');
INSERT INTO Attack VALUES ('Future Sight', 120, 'Psychic');
INSERT INTO Attack VALUES ('Rock Smash', 40, 'Fighting');
INSERT INTO Attack VALUES ('Whirlpool', 35, 'Water');
INSERT INTO Attack VALUES ('Beat Up', , 'Dark');
INSERT INTO Attack VALUES ('Fake Out', 40, 'Normal');
INSERT INTO Attack VALUES ('Uproar', 90, 'Normal');
INSERT INTO Attack VALUES ('Stockpile', , 'Normal');
INSERT INTO Attack VALUES ('Spit Up', , 'Normal');
INSERT INTO Attack VALUES ('Swallow', , 'Normal');
INSERT INTO Attack VALUES ('Heat Wave', 95, 'Fire');
INSERT INTO Attack VALUES ('Hail', , 'Ice');
INSERT INTO Attack VALUES ('Torment', , 'Dark');
INSERT INTO Attack VALUES ('Flatter', , 'Dark');
INSERT INTO Attack VALUES ('Will-O-Wisp', , 'Fire');
INSERT INTO Attack VALUES ('Memento', , 'Dark');
INSERT INTO Attack VALUES ('Facade', 70, 'Normal');
INSERT INTO Attack VALUES ('Focus Punch', 150, 'Fighting');
INSERT INTO Attack VALUES ('Smelling Salts', 70, 'Normal');
INSERT INTO Attack VALUES ('Follow Me', , 'Normal');
INSERT INTO Attack VALUES ('Nature Power', , 'Normal');
INSERT INTO Attack VALUES ('Charge', , 'Electric');
INSERT INTO Attack VALUES ('Taunt', , 'Dark');
INSERT INTO Attack VALUES ('Helping Hand', , 'Normal');
INSERT INTO Attack VALUES ('Trick', , 'Psychic');
INSERT INTO Attack VALUES ('Role Play', , 'Psychic');
INSERT INTO Attack VALUES ('Wish', , 'Normal');
INSERT INTO Attack VALUES ('Assist', , 'Normal');
INSERT INTO Attack VALUES ('Ingrain', , 'Grass');
INSERT INTO Attack VALUES ('Superpower', 120, 'Fighting');
INSERT INTO Attack VALUES ('Magic Coat', , 'Psychic');
INSERT INTO Attack VALUES ('Recycle', , 'Normal');
INSERT INTO Attack VALUES ('Revenge', 60, 'Fighting');
INSERT INTO Attack VALUES ('Brick Break', 75, 'Fighting');
INSERT INTO Attack VALUES ('Yawn', , 'Normal');
INSERT INTO Attack VALUES ('Knock Off', 65, 'Dark');
INSERT INTO Attack VALUES ('Endeavor', , 'Normal');
INSERT INTO Attack VALUES ('Eruption', , 'Fire');
INSERT INTO Attack VALUES ('Skill Swap', , 'Psychic');
INSERT INTO Attack VALUES ('Imprison', , 'Psychic');
INSERT INTO Attack VALUES ('Refresh', , 'Normal');
INSERT INTO Attack VALUES ('Grudge', , 'Ghost');
INSERT INTO Attack VALUES ('Snatch', , 'Dark');
INSERT INTO Attack VALUES ('Secret Power', 70, 'Normal');
INSERT INTO Attack VALUES ('Dive', 80, 'Water');
INSERT INTO Attack VALUES ('Arm Thrust', 15, 'Fighting');
INSERT INTO Attack VALUES ('Camouflage', , 'Normal');
INSERT INTO Attack VALUES ('Tail Glow', , 'Bug');
INSERT INTO Attack VALUES ('Luster Purge', 70, 'Psychic');
INSERT INTO Attack VALUES ('Mist Ball', 70, 'Psychic');
INSERT INTO Attack VALUES ('Feather Dance', , 'Flying');
INSERT INTO Attack VALUES ('Teeter Dance', , 'Normal');
INSERT INTO Attack VALUES ('Blaze Kick', 85, 'Fire');
INSERT INTO Attack VALUES ('Mud Sport', , 'Ground');
INSERT INTO Attack VALUES ('Ice Ball', 30, 'Ice');
INSERT INTO Attack VALUES ('Needle Arm', 60, 'Grass');
INSERT INTO Attack VALUES ('Slack Off', , 'Normal');
INSERT INTO Attack VALUES ('Hyper Voice', 90, 'Normal');
INSERT INTO Attack VALUES ('Poison Fang', 50, 'Poison');
INSERT INTO Attack VALUES ('Crush Claw', 75, 'Normal');
INSERT INTO Attack VALUES ('Blast Burn', 150, 'Fire');
INSERT INTO Attack VALUES ('Hydro Cannon', 150, 'Water');
INSERT INTO Attack VALUES ('Meteor Mash', 90, 'Steel');
INSERT INTO Attack VALUES ('Astonish', 30, 'Ghost');
INSERT INTO Attack VALUES ('Weather Ball', 50, 'Normal');
INSERT INTO Attack VALUES ('Aromatherapy', , 'Grass');
INSERT INTO Attack VALUES ('Fake Tears', , 'Dark');
INSERT INTO Attack VALUES ('Air Cutter', 60, 'Flying');
INSERT INTO Attack VALUES ('Overheat', 130, 'Fire');
INSERT INTO Attack VALUES ('Odor Sleuth', , 'Normal');
INSERT INTO Attack VALUES ('Rock Tomb', 60, 'Rock');
INSERT INTO Attack VALUES ('Silver Wind', 60, 'Bug');
INSERT INTO Attack VALUES ('Metal Sound', , 'Steel');
INSERT INTO Attack VALUES ('Grass Whistle', , 'Grass');
INSERT INTO Attack VALUES ('Tickle', , 'Normal');
INSERT INTO Attack VALUES ('Cosmic Power', , 'Psychic');
INSERT INTO Attack VALUES ('Water Spout', , 'Water');
INSERT INTO Attack VALUES ('Signal Beam', 75, 'Bug');
INSERT INTO Attack VALUES ('Shadow Punch', 60, 'Ghost');
INSERT INTO Attack VALUES ('Extrasensory', 80, 'Psychic');
INSERT INTO Attack VALUES ('Sky Uppercut', 85, 'Fighting');
INSERT INTO Attack VALUES ('Sand Tomb', 35, 'Ground');
INSERT INTO Attack VALUES ('Sheer Cold', , 'Ice');
INSERT INTO Attack VALUES ('Muddy Water', 90, 'Water');
INSERT INTO Attack VALUES ('Bullet Seed', 25, 'Grass');
INSERT INTO Attack VALUES ('Aerial Ace', 60, 'Flying');
INSERT INTO Attack VALUES ('Icicle Spear', 25, 'Ice');
INSERT INTO Attack VALUES ('Iron Defense', , 'Steel');
INSERT INTO Attack VALUES ('Block', , 'Normal');
INSERT INTO Attack VALUES ('Howl', , 'Normal');
INSERT INTO Attack VALUES ('Dragon Claw', 80, 'Dragon');
INSERT INTO Attack VALUES ('Frenzy Plant', 150, 'Grass');
INSERT INTO Attack VALUES ('Bulk Up', , 'Fighting');
INSERT INTO Attack VALUES ('Bounce', 85, 'Flying');
INSERT INTO Attack VALUES ('Mud Shot', 55, 'Ground');
INSERT INTO Attack VALUES ('Poison Tail', 50, 'Poison');
INSERT INTO Attack VALUES ('Covet', 60, 'Normal');
INSERT INTO Attack VALUES ('Volt Tackle', 120, 'Electric');
INSERT INTO Attack VALUES ('Magical Leaf', 60, 'Grass');
INSERT INTO Attack VALUES ('Water Sport', , 'Water');
INSERT INTO Attack VALUES ('Calm Mind', , 'Psychic');
INSERT INTO Attack VALUES ('Leaf Blade', 90, 'Grass');
INSERT INTO Attack VALUES ('Dragon Dance', , 'Dragon');
INSERT INTO Attack VALUES ('Rock Blast', 25, 'Rock');
INSERT INTO Attack VALUES ('Shock Wave', 60, 'Electric');
INSERT INTO Attack VALUES ('Water Pulse', 60, 'Water');
INSERT INTO Attack VALUES ('Doom Desire', 140, 'Steel');
INSERT INTO Attack VALUES ('Psycho Boost', 140, 'Psychic');
INSERT INTO Attack VALUES ('Roost', , 'Flying');
INSERT INTO Attack VALUES ('Gravity', , 'Psychic');
INSERT INTO Attack VALUES ('Miracle Eye', , 'Psychic');
INSERT INTO Attack VALUES ('Wake-Up Slap', 70, 'Fighting');
INSERT INTO Attack VALUES ('Hammer Arm', 100, 'Fighting');
INSERT INTO Attack VALUES ('Gyro Ball', , 'Steel');
INSERT INTO Attack VALUES ('Healing Wish', , 'Psychic');
INSERT INTO Attack VALUES ('Brine', 65, 'Water');
INSERT INTO Attack VALUES ('Natural Gift', , 'Normal');
INSERT INTO Attack VALUES ('Feint', 30, 'Normal');
INSERT INTO Attack VALUES ('Pluck', 60, 'Flying');
INSERT INTO Attack VALUES ('Tailwind', , 'Flying');
INSERT INTO Attack VALUES ('Acupressure', , 'Normal');
INSERT INTO Attack VALUES ('Metal Burst', , 'Steel');
INSERT INTO Attack VALUES ('U-turn', 70, 'Bug');
INSERT INTO Attack VALUES ('Close Combat', 120, 'Fighting');
INSERT INTO Attack VALUES ('Payback', 50, 'Dark');
INSERT INTO Attack VALUES ('Assurance', 60, 'Dark');
INSERT INTO Attack VALUES ('Embargo', , 'Dark');
INSERT INTO Attack VALUES ('Fling', , 'Dark');
INSERT INTO Attack VALUES ('Psycho Shift', , 'Psychic');
INSERT INTO Attack VALUES ('Trump Card', , 'Normal');
INSERT INTO Attack VALUES ('Heal Block', , 'Psychic');
INSERT INTO Attack VALUES ('Wring Out', , 'Normal');
INSERT INTO Attack VALUES ('Power Trick', , 'Psychic');
INSERT INTO Attack VALUES ('Gastro Acid', , 'Poison');
INSERT INTO Attack VALUES ('Lucky Chant', , 'Normal');
INSERT INTO Attack VALUES ('Me First', , 'Normal');
INSERT INTO Attack VALUES ('Copycat', , 'Normal');
INSERT INTO Attack VALUES ('Power Swap', , 'Psychic');
INSERT INTO Attack VALUES ('Guard Swap', , 'Psychic');
INSERT INTO Attack VALUES ('Punishment', , 'Dark');
INSERT INTO Attack VALUES ('Last Resort', 140, 'Normal');
INSERT INTO Attack VALUES ('Worry Seed', , 'Grass');
INSERT INTO Attack VALUES ('Sucker Punch', 80, 'Dark');
INSERT INTO Attack VALUES ('Toxic Spikes', , 'Poison');
INSERT INTO Attack VALUES ('Heart Swap', , 'Psychic');
INSERT INTO Attack VALUES ('Aqua Ring', , 'Water');
INSERT INTO Attack VALUES ('Magnet Rise', , 'Electric');
INSERT INTO Attack VALUES ('Flare Blitz', 120, 'Fire');
INSERT INTO Attack VALUES ('Force Palm', 60, 'Fighting');
INSERT INTO Attack VALUES ('Aura Sphere', 80, 'Fighting');
INSERT INTO Attack VALUES ('Rock Polish', , 'Rock');
INSERT INTO Attack VALUES ('Poison Jab', 80, 'Poison');
INSERT INTO Attack VALUES ('Dark Pulse', 80, 'Dark');
INSERT INTO Attack VALUES ('Night Slash', 70, 'Dark');
INSERT INTO Attack VALUES ('Aqua Tail', 90, 'Water');
INSERT INTO Attack VALUES ('Seed Bomb', 80, 'Grass');
INSERT INTO Attack VALUES ('Air Slash', 75, 'Flying');
INSERT INTO Attack VALUES ('X-Scissor', 80, 'Bug');
INSERT INTO Attack VALUES ('Bug Buzz', 90, 'Bug');
INSERT INTO Attack VALUES ('Dragon Pulse', 85, 'Dragon');
INSERT INTO Attack VALUES ('Dragon Rush', 100, 'Dragon');
INSERT INTO Attack VALUES ('Power Gem', 80, 'Rock');
INSERT INTO Attack VALUES ('Drain Punch', 75, 'Fighting');
INSERT INTO Attack VALUES ('Vacuum Wave', 40, 'Fighting');
INSERT INTO Attack VALUES ('Focus Blast', 120, 'Fighting');
INSERT INTO Attack VALUES ('Energy Ball', 90, 'Grass');
INSERT INTO Attack VALUES ('Brave Bird', 120, 'Flying');
INSERT INTO Attack VALUES ('Earth Power', 90, 'Ground');
INSERT INTO Attack VALUES ('Switcheroo', , 'Dark');
INSERT INTO Attack VALUES ('Giga Impact', 150, 'Normal');
INSERT INTO Attack VALUES ('Nasty Plot', , 'Dark');
INSERT INTO Attack VALUES ('Bullet Punch', 40, 'Steel');
INSERT INTO Attack VALUES ('Avalanche', 60, 'Ice');
INSERT INTO Attack VALUES ('Ice Shard', 40, 'Ice');
INSERT INTO Attack VALUES ('Shadow Claw', 70, 'Ghost');
INSERT INTO Attack VALUES ('Thunder Fang', 65, 'Electric');
INSERT INTO Attack VALUES ('Ice Fang', 65, 'Ice');
INSERT INTO Attack VALUES ('Fire Fang', 65, 'Fire');
INSERT INTO Attack VALUES ('Shadow Sneak', 40, 'Ghost');
INSERT INTO Attack VALUES ('Mud Bomb', 65, 'Ground');
INSERT INTO Attack VALUES ('Psycho Cut', 70, 'Psychic');
INSERT INTO Attack VALUES ('Zen Headbutt', 80, 'Psychic');
INSERT INTO Attack VALUES ('Mirror Shot', 65, 'Steel');
INSERT INTO Attack VALUES ('Flash Cannon', 80, 'Steel');
INSERT INTO Attack VALUES ('Rock Climb', 90, 'Normal');
INSERT INTO Attack VALUES ('Defog', , 'Flying');
INSERT INTO Attack VALUES ('Trick Room', , 'Psychic');
INSERT INTO Attack VALUES ('Draco Meteor', 130, 'Dragon');
INSERT INTO Attack VALUES ('Discharge', 80, 'Electric');
INSERT INTO Attack VALUES ('Lava Plume', 80, 'Fire');
INSERT INTO Attack VALUES ('Leaf Storm', 130, 'Grass');
INSERT INTO Attack VALUES ('Power Whip', 120, 'Grass');
INSERT INTO Attack VALUES ('Rock Wrecker', 150, 'Rock');
INSERT INTO Attack VALUES ('Cross Poison', 70, 'Poison');
INSERT INTO Attack VALUES ('Gunk Shot', 120, 'Poison');
INSERT INTO Attack VALUES ('Iron Head', 80, 'Steel');
INSERT INTO Attack VALUES ('Magnet Bomb', 60, 'Steel');
INSERT INTO Attack VALUES ('Stone Edge', 100, 'Rock');
INSERT INTO Attack VALUES ('Captivate', , 'Normal');
INSERT INTO Attack VALUES ('Stealth Rock', , 'Rock');
INSERT INTO Attack VALUES ('Grass Knot', , 'Grass');
INSERT INTO Attack VALUES ('Chatter', 65, 'Flying');
INSERT INTO Attack VALUES ('Judgment', 100, 'Normal');
INSERT INTO Attack VALUES ('Bug Bite', 60, 'Bug');
INSERT INTO Attack VALUES ('Charge Beam', 50, 'Electric');
INSERT INTO Attack VALUES ('Wood Hammer', 120, 'Grass');
INSERT INTO Attack VALUES ('Aqua Jet', 40, 'Water');
INSERT INTO Attack VALUES ('Attack Order', 90, 'Bug');
INSERT INTO Attack VALUES ('Defend Order', , 'Bug');
INSERT INTO Attack VALUES ('Heal Order', , 'Bug');
INSERT INTO Attack VALUES ('Head Smash', 150, 'Rock');
INSERT INTO Attack VALUES ('Double Hit', 35, 'Normal');
INSERT INTO Attack VALUES ('Roar of Time', 150, 'Dragon');
INSERT INTO Attack VALUES ('Spacial Rend', 100, 'Dragon');
INSERT INTO Attack VALUES ('Lunar Dance', , 'Psychic');
INSERT INTO Attack VALUES ('Crush Grip', , 'Normal');
INSERT INTO Attack VALUES ('Magma Storm', 100, 'Fire');
INSERT INTO Attack VALUES ('Dark Void', , 'Dark');
INSERT INTO Attack VALUES ('Seed Flare', 120, 'Grass');
INSERT INTO Attack VALUES ('Ominous Wind', 60, 'Ghost');
INSERT INTO Attack VALUES ('Shadow Force', 120, 'Ghost');
INSERT INTO Attack VALUES ('Hone Claws', , 'Dark');
INSERT INTO Attack VALUES ('Wide Guard', , 'Rock');
INSERT INTO Attack VALUES ('Guard Split', , 'Psychic');
INSERT INTO Attack VALUES ('Power Split', , 'Psychic');
INSERT INTO Attack VALUES ('Wonder Room', , 'Psychic');
INSERT INTO Attack VALUES ('Psyshock', 80, 'Psychic');
INSERT INTO Attack VALUES ('Venoshock', 65, 'Poison');
INSERT INTO Attack VALUES ('Autotomize', , 'Steel');
INSERT INTO Attack VALUES ('Rage Powder', , 'Bug');
INSERT INTO Attack VALUES ('Telekinesis', , 'Psychic');
INSERT INTO Attack VALUES ('Magic Room', , 'Psychic');
INSERT INTO Attack VALUES ('Smack Down', 50, 'Rock');
INSERT INTO Attack VALUES ('Storm Throw', 60, 'Fighting');
INSERT INTO Attack VALUES ('Flame Burst', 70, 'Fire');
INSERT INTO Attack VALUES ('Sludge Wave', 95, 'Poison');
INSERT INTO Attack VALUES ('Quiver Dance', , 'Bug');
INSERT INTO Attack VALUES ('Heavy Slam', , 'Steel');
INSERT INTO Attack VALUES ('Synchronoise', 120, 'Psychic');
INSERT INTO Attack VALUES ('Electro Ball', , 'Electric');
INSERT INTO Attack VALUES ('Soak', , 'Water');
INSERT INTO Attack VALUES ('Flame Charge', 50, 'Fire');
INSERT INTO Attack VALUES ('Coil', , 'Poison');
INSERT INTO Attack VALUES ('Low Sweep', 65, 'Fighting');
INSERT INTO Attack VALUES ('Acid Spray', 40, 'Poison');
INSERT INTO Attack VALUES ('Foul Play', 95, 'Dark');
INSERT INTO Attack VALUES ('Simple Beam', , 'Normal');
INSERT INTO Attack VALUES ('Entrainment', , 'Normal');
INSERT INTO Attack VALUES ('After You', , 'Normal');
INSERT INTO Attack VALUES ('Round', 60, 'Normal');
INSERT INTO Attack VALUES ('Echoed Voice', 40, 'Normal');
INSERT INTO Attack VALUES ('Chip Away', 70, 'Normal');
INSERT INTO Attack VALUES ('Clear Smog', 50, 'Poison');
INSERT INTO Attack VALUES ('Stored Power', 20, 'Psychic');
INSERT INTO Attack VALUES ('Quick Guard', , 'Fighting');
INSERT INTO Attack VALUES ('Ally Switch', , 'Psychic');
INSERT INTO Attack VALUES ('Scald', 80, 'Water');
INSERT INTO Attack VALUES ('Shell Smash', , 'Normal');
INSERT INTO Attack VALUES ('Heal Pulse', , 'Psychic');
INSERT INTO Attack VALUES ('Hex', 65, 'Ghost');
INSERT INTO Attack VALUES ('Sky Drop', 60, 'Flying');
INSERT INTO Attack VALUES ('Shift Gear', , 'Steel');
INSERT INTO Attack VALUES ('Circle Throw', 60, 'Fighting');
INSERT INTO Attack VALUES ('Incinerate', 60, 'Fire');
INSERT INTO Attack VALUES ('Quash', , 'Dark');
INSERT INTO Attack VALUES ('Acrobatics', 55, 'Flying');
INSERT INTO Attack VALUES ('Reflect Type', , 'Normal');
INSERT INTO Attack VALUES ('Retaliate', 70, 'Normal');
INSERT INTO Attack VALUES ('Final Gambit', , 'Fighting');
INSERT INTO Attack VALUES ('Bestow', , 'Normal');
INSERT INTO Attack VALUES ('Inferno', 100, 'Fire');
INSERT INTO Attack VALUES ('Water Pledge', 80, 'Water');
INSERT INTO Attack VALUES ('Fire Pledge', 80, 'Fire');
INSERT INTO Attack VALUES ('Grass Pledge', 80, 'Grass');
INSERT INTO Attack VALUES ('Volt Switch', 70, 'Electric');
INSERT INTO Attack VALUES ('Struggle Bug', 50, 'Bug');
INSERT INTO Attack VALUES ('Bulldoze', 60, 'Ground');
INSERT INTO Attack VALUES ('Frost Breath', 60, 'Ice');
INSERT INTO Attack VALUES ('Dragon Tail', 60, 'Dragon');
INSERT INTO Attack VALUES ('Work Up', , 'Normal');
INSERT INTO Attack VALUES ('Electroweb', 55, 'Electric');
INSERT INTO Attack VALUES ('Wild Charge', 90, 'Electric');
INSERT INTO Attack VALUES ('Drill Run', 80, 'Ground');
INSERT INTO Attack VALUES ('Dual Chop', 40, 'Dragon');
INSERT INTO Attack VALUES ('Heart Stamp', 60, 'Psychic');
INSERT INTO Attack VALUES ('Horn Leech', 75, 'Grass');
INSERT INTO Attack VALUES ('Sacred Sword', 90, 'Fighting');
INSERT INTO Attack VALUES ('Razor Shell', 75, 'Water');
INSERT INTO Attack VALUES ('Heat Crash', , 'Fire');
INSERT INTO Attack VALUES ('Leaf Tornado', 65, 'Grass');
INSERT INTO Attack VALUES ('Steamroller', 65, 'Bug');
INSERT INTO Attack VALUES ('Cotton Guard', , 'Grass');
INSERT INTO Attack VALUES ('Night Daze', 85, 'Dark');
INSERT INTO Attack VALUES ('Psystrike', 100, 'Psychic');
INSERT INTO Attack VALUES ('Tail Slap', 25, 'Normal');
INSERT INTO Attack VALUES ('Hurricane', 110, 'Flying');
INSERT INTO Attack VALUES ('Head Charge', 120, 'Normal');
INSERT INTO Attack VALUES ('Gear Grind', 50, 'Steel');
INSERT INTO Attack VALUES ('Searing Shot', 100, 'Fire');
INSERT INTO Attack VALUES ('Techno Blast', 120, 'Normal');
INSERT INTO Attack VALUES ('Relic Song', 75, 'Normal');
INSERT INTO Attack VALUES ('Secret Sword', 85, 'Fighting');
INSERT INTO Attack VALUES ('Glaciate', 65, 'Ice');
INSERT INTO Attack VALUES ('Bolt Strike', 130, 'Electric');
INSERT INTO Attack VALUES ('Blue Flare', 130, 'Fire');
INSERT INTO Attack VALUES ('Fiery Dance', 80, 'Fire');
INSERT INTO Attack VALUES ('Freeze Shock', 140, 'Ice');
INSERT INTO Attack VALUES ('Ice Burn', 140, 'Ice');
INSERT INTO Attack VALUES ('Snarl', 55, 'Dark');
INSERT INTO Attack VALUES ('Icicle Crash', 85, 'Ice');
INSERT INTO Attack VALUES ('V-create', 180, 'Fire');
INSERT INTO Attack VALUES ('Fusion Flare', 100, 'Fire');
INSERT INTO Attack VALUES ('Fusion Bolt', 100, 'Electric');
INSERT INTO Attack VALUES ('Flying Press', 80, 'Fighting');
INSERT INTO Attack VALUES ('Mat Block', , 'Fighting');
INSERT INTO Attack VALUES ('Belch', 120, 'Poison');
INSERT INTO Attack VALUES ('Rototiller', , 'Ground');
INSERT INTO Attack VALUES ('Sticky Web', , 'Bug');
INSERT INTO Attack VALUES ('Fell Stinger', 30, 'Bug');
INSERT INTO Attack VALUES ('Phantom Force', 90, 'Ghost');
INSERT INTO Attack VALUES ('Trick-or-Treat', , 'Ghost');
INSERT INTO Attack VALUES ('Noble Roar', , 'Normal');
INSERT INTO Attack VALUES ('Ion Deluge', , 'Electric');
INSERT INTO Attack VALUES ('Parabolic Charge', 50, 'Electric');
INSERT INTO Attack VALUES ('Forests Curse', , 'Grass');
INSERT INTO Attack VALUES ('Petal Blizzard', 90, 'Grass');
INSERT INTO Attack VALUES ('Freeze-Dry', 70, 'Ice');
INSERT INTO Attack VALUES ('Disarming Voice', 40, 'Fairy');
INSERT INTO Attack VALUES ('Parting Shot', , 'Dark');
INSERT INTO Attack VALUES ('Topsy-Turvy', , 'Dark');
INSERT INTO Attack VALUES ('Draining Kiss', 50, 'Fairy');
INSERT INTO Attack VALUES ('Crafty Shield', , 'Fairy');
INSERT INTO Attack VALUES ('Flower Shield', , 'Fairy');
INSERT INTO Attack VALUES ('Grassy Terrain', , 'Grass');
INSERT INTO Attack VALUES ('Misty Terrain', , 'Fairy');
INSERT INTO Attack VALUES ('Electrify', , 'Electric');
INSERT INTO Attack VALUES ('Play Rough', 90, 'Fairy');
INSERT INTO Attack VALUES ('Fairy Wind', 40, 'Fairy');
INSERT INTO Attack VALUES ('Moonblast', 95, 'Fairy');
INSERT INTO Attack VALUES ('Boomburst', 140, 'Normal');
INSERT INTO Attack VALUES ('Fairy Lock', , 'Fairy');
INSERT INTO Attack VALUES ('Kings Shield', , 'Steel');
INSERT INTO Attack VALUES ('Play Nice', , 'Normal');
INSERT INTO Attack VALUES ('Confide', , 'Normal');
INSERT INTO Attack VALUES ('Diamond Storm', 100, 'Rock');
INSERT INTO Attack VALUES ('Steam Eruption', 110, 'Water');
INSERT INTO Attack VALUES ('Hyperspace Hole', 80, 'Psychic');
INSERT INTO Attack VALUES ('Water Shuriken', 15, 'Water');
INSERT INTO Attack VALUES ('Mystical Fire', 65, 'Fire');
INSERT INTO Attack VALUES ('Spiky Shield', , 'Grass');
INSERT INTO Attack VALUES ('Aromatic Mist', , 'Fairy');
INSERT INTO Attack VALUES ('Eerie Impulse', , 'Electric');
INSERT INTO Attack VALUES ('Venom Drench', , 'Poison');
INSERT INTO Attack VALUES ('Powder', , 'Bug');
INSERT INTO Attack VALUES ('Geomancy', , 'Fairy');
INSERT INTO Attack VALUES ('Magnetic Flux', , 'Electric');
INSERT INTO Attack VALUES ('Happy Hour', , 'Normal');
INSERT INTO Attack VALUES ('Electric Terrain', , 'Electric');
INSERT INTO Attack VALUES ('Dazzling Gleam', 80, 'Fairy');
INSERT INTO Attack VALUES ('Celebrate', , 'Normal');
INSERT INTO Attack VALUES ('Hold Hands', , 'Normal');
INSERT INTO Attack VALUES ('Baby-Doll Eyes', , 'Fairy');
INSERT INTO Attack VALUES ('Nuzzle', 20, 'Electric');
INSERT INTO Attack VALUES ('Hold Back', 40, 'Normal');
INSERT INTO Attack VALUES ('Infestation', 20, 'Bug');
INSERT INTO Attack VALUES ('Power-Up Punch', 40, 'Fighting');
INSERT INTO Attack VALUES ('Oblivion Wing', 80, 'Flying');
INSERT INTO Attack VALUES ('Thousand Arrows', 90, 'Ground');
INSERT INTO Attack VALUES ('Thousand Waves', 90, 'Ground');
INSERT INTO Attack VALUES ('Lands Wrath', 90, 'Ground');
INSERT INTO Attack VALUES ('Light of Ruin', 140, 'Fairy');
INSERT INTO Attack VALUES ('Origin Pulse', 110, 'Water');
INSERT INTO Attack VALUES ('Precipice Blades', 120, 'Ground');
INSERT INTO Attack VALUES ('Dragon Ascent', 120, 'Flying');
INSERT INTO Attack VALUES ('Hyperspace Fury', 100, 'Dark');
